### ISSUE TITLE
Atelier sur les catégories de composants

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1104]
Définir les catégories de composants à afficher dans la documentation afin de simplifier la recherche d'un composant

**Comment by francoiscoue** [comment]
Support de l'atelier : https://app.mural.co/t/eyadvisory3625/m/eyadvisory3625/1620291538923/32113a0abfac5242b41e47277a54f5016e875884?sender=francoiscoue0974
résultat des catégories: https://www.figma.com/file/gKaLp1f8pMdaf1jcu2mX5R/Design-System-Cnam?node-id=1800%3A61
