### ISSUE TITLE
Atelier sur la page d'accueil de la documentation

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1162]

**Comment by francoiscoue** [comment]
**Documentation**
Introduction -> on a retiré la galerie des composants
• Contenu du design system : composants, composants techniques, bundle (questionnaire/formbuilder)
- Galerie des composants -> quel type de visuels on met dans les vignettes ? • On a des catégories de composants (action,formulaire...)
- Guide designer -> principes de design
- Guide dev -> installation, convention
- Contribution - Roadmap
- Glossaire
- Nomenclature
Validation des fondamentaux
Validation de la classification des composants

maquettes en cours de réalisation ici : https://www.figma.com/file/gKaLp1f8pMdaf1jcu2mX5R/Design-System-Cnam?node-id=449%3A0


**Prochaines étapes**
Doc en anglais ou en français ? -> Faire un premier jet sur les maquettes et demander aux équipe, réunion de 15min par petit groupe (2/3). CPAM Agen, DPRA, team MCO, côté design équipe Price
Créer les pages
