### ISSUE TITLE
Composant Captcha

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1174]
Création d'un composant Captcha en collaboration avec l'équipe DDST.

Dans un premier temps, nous devons fournir une implémentation de l'interface du composant en Vue.js avec Vuetify afin que DDST étudie l'intégration avec leur composant existant.

**Comment by Kelhel** [comment]
Ci-dessous le template html de l'implémentation du composant : 
`<VRow
			align="center"
			class="mt-2"
			no-gutters
		>
			<VBtn
				class="text-none primary--text text-subtitle-2 font-weight-bold"
				plain
				small
			>
				Changer d'image
			</VBtn>

			<span class="text-subtitle-2 mx-1">ou</span>

			<VBtn
				class="text-none primary--text text-subtitle-2 font-weight-bold"
				plain
				small
			>
				Utiliser un captcha audio
			</VBtn>
		</VRow>

		<img
			width="311"
			height="64"
			class="mt-4"
			src="captcha.png"
			alt="File not found"
		>
		
		<VRow
			class="mt-4"
			no-gutters
		>
			<VCol cols="8">
				<VTextField
					placeholder="Caractères de l'image"
					outlined
					clearable
				/>
			</VCol>
		</VRow>`

**Comment by deraw** [comment]
Le composant a été réalisé en interne par l'équipe DDST.
