### ISSUE TITLE
Atelier définition sprint

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1187]

**Comment by Becqueva** [comment]
Atelier déf. sprint
Compte-rendu du 24/06/2021

Design system (équipe)
Penser faire 2 sprints de 15 jours et une release par mois.
1 MEP / Mois (arrive avant la démo / lundi matin)
1er et 3ème lundi de chaque mois début du sprint

Sujet : Comment on met ça en place, qu'est-ce qu'il nous faut pour démarrer ?
Equipe scrum - organisation

Liste fourniture : 
Outil de gestion de projet : Jira/Github 
Pour prendre des notes / besoin d'un outil autre que Slack = peut-être confluence / ou github (s'il le fait = privilégier)

Faut-il inserer les process de fonctionnement dans la doc ?
Etre prêt à acceuillir une contribution extérieure


Les rôles : 
Scrum master (garant de la méthode) - Kévin
Techlead (garant de la décisionnelle du code) - Dylan
Product Owner (garant de l'harmonisation du projet) - François
Dév - Yvon, Kevin, Aubin

Rituels
Daily - 10h à 10h15
Weekly : Démo / Rétro / Planning - mardi après-midi (3h - enchaînement)
Atelier conception jeudi matin - hebdo et physique - 10h30 > 12h

Démarre le rituel mardi 8

Au sujet des accompagnements (2 jours par semaine / variable en fonction de l'évolution de la taille de l'équipe)
Jours incompressibles 
Assurer une permanence
 
Comment est-ce qu'on gère les contributions ?
Dylan "aujourd'hui, peu de contribution qui arriveront dans notre backlog"
On les gères dans l'accompagnement.

Choisir les US (users stories)/ PO & techlead (puisqu'il peut assurer la faisabilité techno) 
Grooming (alimenter le backlog)

//
To do :
Kevin : 
- documenter les rituels
- vérifier Github 
- documenter outils/process 

François & Dylan & Valentin :
Grooming / rédaction des US

François : Mettre à jour les invitations

Yvon : Documenter les process de contribution (page contribué avec process)
