### ISSUE TITLE
Refonte graphique page d'introduction Documentation

### ISSUE THREAD

**Issue by francoiscoue** [assurance-maladie-digital/design-system#1234]
> En tant que nouveau utilisateur du Design System, je veux comprendre de quoi il s’agit et ce qu’il contient.

**Tâches** : 
- Validation layout 
- Rédaction du contenu de la page intro
- Visuels pour les rubriques
- Intégration

**Maquette** : https://www.figma.com/file/gKaLp1f8pMdaf1jcu2mX5R/Design-System-Cnam?node-id=2314%3A45877

**Comment by Becqueva** [comment]
{ 13/07
Travail de composition graphique
Réflexion sur la pertinence d'avoir un menu "Contenu du Design System" (ou CDS)
Rédaction de la partie "Qu'est-ce qu'un Design System ?"
Ebauche de la partie "Les cinq principes du Design System" 
Conclusion - pour le menu CDS pas d'intérêt opérationnel immédiat
}
{ 15/07
Réflexion menée autour des parties rédactionnelles notamment la partie "Les cinq [...] System"
}

**Comment by Becqueva** [comment]
Lien du Figma : https://www.figma.com/file/gKaLp1f8pMdaf1jcu2mX5R/Design-System-Cnam?node-id=449%3A0
Texte à relire / review
