### ISSUE TITLE
Ajout de l'analytics sur la documentation

### ISSUE THREAD

**Issue by francoiscoue** [assurance-maladie-digital/design-system#1266]
En tant que PO/membre de l'équipe du Design System
Je veux pouvoir mesurer le nombre de visites par page du Design System
Afin de mieux connaître les besoins des utilisateurs et de mesurer la performance du Design System

**Comment by deraw** [comment]
Après avoir testé Google Analytics, il est préférable de s'orienter vers une solution plus respectueuse de la vie privée et qui n'utilise pas de cookies.

Deux choix ont été étudiés :

1. [Plausible](https://plausible.io/)
2. [Netlify Analytics](https://www.netlify.com/products/analytics/)

### Plausible

Plausible est open-source, s'intègre via un script client, peu être hébergé soi-même gratuitement et permet d'avoir des statistiques publiques (https://plausible.io/plausible.io)

### Netlify Analytics

La solution de Netlify ne nécessite pas de script client, tout est fait côté serveur par Netlify.

## Conclusion

Nous allons tester pendant un mois la solution de Netlify, puis faire confirmer ce choix. Si le choix ne peut pas être validé (pas de budget alloué par exemple), nous étudierons un hébergement pour Plausible.
