### ISSUE TITLE
Étudier la mise en place d'une API exemple pour la documentation

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1274]
## Type

- Étude

## Description

En tant que développeur utilisant le Design System, je veux avoir des exemples concrets utilisant une vraie API.

Étudier quelle solution mettre en place (fonctions Netlify, autre service etc).

### Critères de recherche

- Langage TypeScript
- Éventuellement serverless

### Premiers éléments de recherche

Nom de la solution | Netlify | Ts.ED | Strapi | Express | Koa | axios-mock-adapter
-- | -- | -- | -- | -- | -- | --
Site Web | [Netlify](https://www.netlify.com/) | [Ts.ED](https://tsed.io/) | [Strapi](https://strapi.io/) | [Express](http://expressjs.com/) | [Koa](https://koajs.com/) | [axios-mock-adapter](https://www.npmjs.com/package/axios-mock-adapter)
Langage natif | JS/TS | TS | JS  | JS/TS | JS | JS/TS
Serverless | Oui | Non | Non  | Non | Non | Oui

## Déploiement

Pour déployer une application Node.js, il existe plusieurs solutions gratuites comme [Heroku](https://www.heroku.com/pricing), [AWS](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_nodejs.html), [Glitch](https://glitch.com/pricing) ou encore [Google Cloud Plateform](https://cloud.google.com/appengine/).
Pour Netlify, le déploiement des fonctions se passe dans l'outil.

## Conclusion

Il existe de nombreuses offre pour répondre à notre besoin.

Après débat, nous trouvons que la possibilité d'avoir une véritable API est préférable à une solution interne au Design System, notamment pour laisser la possibilité d'ouvrir les requêtes à d'autres applications.

Nous écartons :
- axios-mock-adapter car ce n'est pas une véritable API
- Strapi car plutôt orienté CMS ainsi et absence de solution TypeScript fiable
- Koa car absence d'une solution TypeScript fiable

Les solutions Netlify, Ts.ED et Express répondent toutes à nos critères.

## Résultat

Nous choisissons Netlify car cette solution nous permet de garder une API simple dont le code source vit dans le même repo que la documentation et car cela nous évite de multiplier les outils. De plus, nous avons maintenant un compte Open Source Sponsorisé qui nous offre plus de possibilités.

**Comment by PYKEngine** [comment]
## Premiers éléments de recherche

Nom de la solution | Netlify | Ts.ED | Express
-- | -- | -- | --
site web | [lien direct](https://www.netlify.com/) | [lien direct](https://tsed.io/) | [lien direct](http://expressjs.com/)
