### ISSUE TITLE
Template pour la documentation des fonctions de validation

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1276]
En tant que développeur utilisant le Design System, je veux savoir quelles fonctions de validation sont disponibles dans Vue Dot et comment les utiliser.

Étudier comment documenter les fonctions de validation (signatures, exemples etc)

**Comment by PYKEngine** [comment]
Proposition d'un template reprenant la structure existante de notre documentation (composant api) et reprenant la mise en forme de la documentation d'express.js

![image](https://user-images.githubusercontent.com/46431396/130626640-9e2c98ee-7c3e-4c0d-9978-3852c8bde331.png)
