### ISSUE TITLE
Guide sur la gestion des variables d'environnement

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1279]
En tant que développeur utilisant le Design System, je veux apprendre à ajouter/supprimer et utiliser des variables d'environnement.

Ajouter un nouveau guide "Variables d'environnement" dans la documentation expliquant la gestion des variables d'environnement et leur spécificité (système personnalisé car exécutée au runtime)

**Comment by mmi16389** [comment]
8
