### ISSUE TITLE
Guide sur la récupération et l'utilisation d'un token

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1281]
En tant que développeur utilisant le Design System, je veux apprendre à récupérer et utiliser un token d'authentification.

Ajouter un nouveau guide "Authentification avec token" dans la documentation expliquant comment récupérer un token JWT (dans l'URL, par exemple `#access_token=""`) et comment l'utiliser (le stocker et l'utiliser en header avec axios pour les requêtes).

**Comment by Kelhel** [comment]
Reste à faire :

- Mettre à jour le changelog
- Review
