### ISSUE TITLE
Page principes de design

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1321]
En tant qu'utilisateur du Design System, je veux connaitre les principes de design.

Définition des principes de design permettant de garantir la meilleure expérience utilisateur.

**Comment by Becqueva** [comment]
09/08/21
Survey mené sur les design systems 
41 Design System (DS) comportant une documentation en libre accès identifié
Sélection de 10 DS
(1) Design - Material Design : [lien](https://material.io/design)
(2) Microsoft Design : [lien](https://www.microsoft.com/design/fluent/#/)
(3) Atlassian Design System : [lien](https://atlassian.design/)
(4) Carbon Design System : [lien](https://www.carbondesignsystem.com/)
(5) AXA Digital Guidelines and Design System : [lien](https://design.axa.com/)
(6) Design System Doctolib : [lien](https://oxygen.doctolib.design/60b411768/p/77fd2d-design-system-doctolib)
(7) Engie Design : [lien](https://www.engie.design/fluid-design-system/)
(8) Prisme : [lien](http://prisme.lucca.io/home)
(9) Saphir V.2 : [lien](https://zeroheight.com/5a173cb79/p/75632e-saphir-v2)
(10) Design System - Maif : [lien](https://design.maif.fr/design-system.html) 

Préférence personnelle pour le DS n°7 : Engie Design
Un niveau de DS aux objectifs atteignables et en cohérence avec le travail déjà engagé.

**Comment by Becqueva** [comment]
11/08/21
Page crée dans Figma : https://www.figma.com/file/7vwtiPk0ELP81BRC3bf5hC/Documentation?node-id=3%3A4199

Choix de trois principes : 
(1) Être au service des usagers de la santé publique
(2) Assurer l’accessibilité pour tous
(3) Rendre évident ce qui est complexe

Rédaction du contenu suivant la forme suivante (avec un icône au second paragraphe) : 
Premier paragraphe : Ambition 
Selon paragraphe : Description, recommandation et conseils
Ordre de lecture du second paragraphe
Nous recommandons pour chaque utilisation de notre Design System [...].
Afin d’accompagner celles et ceux qui le souhaitent, nous pouvons [...].
