### ISSUE TITLE
Ajout de la recherche avec Algolia

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1425]
En tant qu'utilisateur du Design System, je veux pouvoir rechercher une information rapidement.

Ajouter la recherche avec Algolia (solution open-source [DocSearch](https://docsearch.algolia.com/)).

**Comment by Becqueva** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-60d49114beeb9300125e9324/issues/assurance-maladie-digital/design-system/1425?planning-poker) with ZenHub @deraw @francoiscoue @Kelhel @mmi16389
