### ISSUE TITLE
Documentation des classes utilitaires CSS

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1523]
En tant que développeur utilisant le Design System, je veux savoir quelles sont les classes utilitaires disponibles et leur utilité.

**Comment by Kelhel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-60d49114beeb9300125e9324/issues/assurance-maladie-digital/design-system/1523?planning-poker) with ZenHub @deraw @mmi16389
