### ISSUE TITLE
Création de la page sur l'accessibilité

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1622]
En tant qu'utilisateur du Design System, je veux connaître le référentiel relatif à l'accessibilité et le niveau visé.

Maquette Figma : https://www.figma.com/file/7vwtiPk0ELP81BRC3bf5hC/Documentation?node-id=501%3A23452

**Comment by Kelhel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-60d49114beeb9300125e9324/issues/assurance-maladie-digital/design-system/1622?planning-poker) with ZenHub @deraw @mmi16389

**Comment by Becqueva** [comment]
10/01/2022
Finalisation de la v1
