### ISSUE TITLE
Intégration du composant Footer version complexe

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1624]
US urgente

**Comment by Kelhel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-60d49114beeb9300125e9324/issues/assurance-maladie-digital/design-system/1624?planning-poker) with ZenHub @deraw @mmi16389

**Comment by Becqueva** [comment]
En tant que client PO je veux pouvoir intégrer un footer large pour mon produit.

Cette demande intervient dans le cadre du produit compte entreprise. C'est une demande urgente.

Lien maquette : https://www.figma.com/file/gKaLp1f8pMdaf1jcu2mX5R/Design-System-Cnam---Composants?node-id=5733%3A67023

Review à faire avec Valentin
