### ISSUE TITLE
Documentation des bonnes pratiques d'accessibilité côté dev

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1625]
En tant qu'utilisateur du Design System, je veux connaître les bonnes pratiques générales côté développement.

**Comment by Kelhel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-60d49114beeb9300125e9324/issues/assurance-maladie-digital/design-system/1625?planning-poker) with ZenHub @deraw @mmi16389
