### ISSUE TITLE
Documenter les outils de développement

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#1626]
En tant que développeur utilisant le Design System, je veux connaître les outils et extensions utilisés par les équipes de développement.

**Comment by Kelhel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-60d49114beeb9300125e9324/issues/assurance-maladie-digital/design-system/1626?planning-poker) with ZenHub @deraw @mmi16389
