### ISSUE TITLE
Liens externes de la documentation

### ISSUE THREAD

**Issue by maximedeoliveira** [assurance-maladie-digital/design-system#1635]
## Description

Les liens externes de la documentation ne redirigent pas vers la bonne page. 

Actuellement, au clic sur "framework Vue.js" de la page [introduction](https://digital-design-system.netlify.app/demarrer/introduction) nous sommes redirigés vers l'URL suivante 
```
https://digital-design-system.netlify.app/demarrer/introduction/#https:fr.vuejs.org
```
au lieu de 
```
https://fr.vuejs.org
```
L'exemple ci-dessus fonctionne pour l'ensemble des liens externes de la documentation.

## Comment reproduire

1. Allez sur la documentation
2. Cliquez sur un lien externe

## Comportement attendu

Lors du clic sur un lien externe, on devrait être redirigé vers la bonne page.

## Priorisation

- Peu prioritaire

**Comment by deraw** [comment]
Merci pour le rapport de bug, ça sera corrigé lors de notre prochain déploiement !
