### ISSUE TITLE
Bug d'affichage sur le DatePicker

### ISSUE THREAD

**Issue by Kelhel** [assurance-maladie-digital/design-system#1664]
## Description

Bug sur l'affichage d'une date sur le DatePicker

## Comment reproduire

1. Ouvrir une page avec le composant DatePicker
2. Saisir la date 01/01/0999, le champs se vide automatiquement

Autre problème :
1. Ouvrir une page avec le composant DatePicker
2. Saisir une date valide (ex 01/01/2000)
3. Quitter le champs, puis saisir à dedans 01/01/0999
4. Affichage de `invalidDate` dans le champs

## Captures d'écran

![image](https://user-images.githubusercontent.com/56488255/145839611-cd53a79f-ca04-45d2-bc0a-39779ea773cf.png)

## Priorisation

- Prioritaire

**Comment by deraw** [comment]
J'ai corrigé le comportement du `DatePicker` en gérant l'erreur et en affichant un message d'erreur pour indiquer que la date n'est pas valide.
Cependant la date devrait être valide, elle ne l'est pas car lors du formatage avec Day.js, il retourne l'année sur 3 chiffres au lieu de 4, ce qui ne respecte pas le format attendu.
J'ai ouvert une issue sur leur repo https://github.com/iamkun/dayjs/issues/1849
