### ISSUE TITLE
Ajout du lien "plan de site" dans la FooterBar

### ISSUE THREAD

**Issue by Becqueva** [assurance-maladie-digital/design-system#1857]
Pour répondre aux enjeux de l'accessibilité je veux pouvoir disposer du lien vers le plan de site directement, si je le souhaite, via le footer. 

Je peux bien sûr décider de ne pas activer cette brique en cas de site très léger (< 5 pages ou parcours unique) et afficher directement les pages dans le footer en version large.

**Comment by deraw** [comment]
Attention à bien communiquer la modification à la publication de la version
