### ISSUE TITLE
Variation du composant Upload

### ISSUE THREAD

**Issue by Becqueva** [assurance-maladie-digital/design-system#1882]
En tant qu'utilisateur du compte entreprise, j'ai besoin de pouvoir avoir simultanément en visibilité 
- les pièces requises
- les pièces optionnelles 
- un feedback des pièces non anticipées mais déposées par moi

Par ailleurs, je dois pouvoir avoir des espaces de légende pour décrire soit l'action attendue par l'utilisateur, soit l'explication du comportement (nature de la pièce et/ou son statut) de l'affichage des pièces.

Je veux également ne pas à avoir à re-sélectionner la nature de la pièce lorsque je clique sur le pictogramme associé à un dépôt spécifique (ligne de la pièce demandée).
Cette option est néanmoins à conserver pour la zone de drag and drop.

**Comment by deraw** [comment]
Il faudrait également prévoir une limite de nombre fichiers maximum et une limite de taille totale

**Comment by Becqueva** [comment]
Changements légers dans un premier temps puis v2 à prévoir
