### ISSUE TITLE
Date "autocorrigée" dans le DatePicker

### ISSUE THREAD

**Issue by juliennicouleaud** [assurance-maladie-digital/design-system#2033]
## Description

Quand je renseigne une date "impossible" dans le DatePicker, elle est automatiquement corrigée pour être remplacée par une date "possible" ce qui pourrait entraîner des erreurs de saisie.

## Comment reproduire

1. Saisir une date du type 10/13/2022 dans le champ DatePicker
2. Cliquer en dehors du champ
3. La valeur est remplacée par 10/01/2023
(c'est comme si le date picker ajoutait ce qui est en trop à "12" (décembre) pour retomber sur une date qui existe)

## Reproduction minimale

Testé ici sur la version 2.4.0 : https://digital-design-system.netlify.app/composants/date-picker

## Comportement attendu

On devrait plutôt voir un message d'erreur qui indique que le mois "13" n'existe pas.

## Environnement

- OS : macOS big Sur
- Navigateur : Chrome 102

## Priorisation

- Prioritaire

## Projet

Design System

**Comment by deraw** [comment]
Hello @juliennicouleaud,

Il s'agit d'un bug venant de la librairie day.js, j'ai ouvert une issue sur leur repo : https://github.com/iamkun/dayjs/issues/1950

Dans le composant le cas d'une date invalide est bien géré via un message d'erreur.
Lorsque le bug sera corrigé dans la librairie nous mettrons à jour de notre côté.

**Comment by deraw** [comment]
Hello @juliennicouleaud,

Le bug a été corrigé, le correctif sera disponible dans la prochaine version que nous publierons bientôt !
