### ISSUE TITLE
collectCoverageFrom exluant des élements du code développé par l'équipe.

### ISSUE THREAD

**Issue by asicfr** [assurance-maladie-digital/design-system#2262]
## Description

La liste d'exclusion jest.config.ts  correspond à exclure les fichiers de la couverture de tests Sonar :

!**/node_modules/**
!**/*.d.ts
!**/decorators.ts
!**/constants/**
!**/router/**
!**/main.ts
!**/theme/**
!**/plugins/**
!**/i18n.ts
!**/store/**
!**/services/**
!**/tests/**
!**/translations/**

Cette liste est un peu trop large.
Y a t'il des raisons d'exclure notamment les services ?
Avez-vous des préconisations spécifiques qui poussent à exclure ces éléments svp ? 

Cordialement

**Comment by asicfr** [comment]
Bonjour,
merci pour la réponse
ca reste du code testable malgré tout ?
Cdl

**Comment by deraw** [comment]
Oui en effet !
Je ne sais pas si on veut le tester par défaut, mais si une PR est proposée on l'acceptera 👀
