### ISSUE TITLE
Ajouter le composant Filtres

### ISSUE THREAD

**Issue by Becqueva** [assurance-maladie-digital/design-system#2287]
Intégration du composant filtres

Voir maquette espace Valentin - contacter V. pour démo

https://www.figma.com/file/gKaLp1f8pMdaf1jcu2mX5R/Design-System-Cnam---Composants?node-id=4983%3A42969

**Comment by Becqueva** [comment]
Reste à faire : 
- Modification sur l'utilisation du composant

**Comment by christopheGaon** [comment]
remettre les deux composants InlineFilters et SideBarFilters dans un repertoire Filters dans les src 
dans les doc c est ok juste reporter les nom InlineFilters et SideBarFilters
xp sur les tests

**Comment by christopheGaon** [comment]
xp sur les tests pour avancer 

separation ok

**Comment by christopheGaon** [comment]
@deraw les tests passent, la separation est faite. On merge ?

**Comment by Becqueva** [comment]
On est où ?

**Comment by Becqueva** [comment]
Le module de filtre devrait être initié dans le sprint prochain du projet compte entreprise. Est-ce qu'il peut être terminé pour jeudi de cette semaine ou est-ce que le produit doit créer le composant en interne ?

**Comment by Becqueva** [comment]
1 semaine de travail prévue pour finaliser

**Comment by Becqueva** [comment]
Relance du PO, as-t-on une visu sur une mise en service du composant ?

**Comment by Becqueva** [comment]
Composant abandonné côté produits (PIMCO, Compte Entreprise et BPIJ-DSIJ), il n'y a plus d'urgence.
