### ISSUE TITLE
Espace sous le FooterBar

### ISSUE THREAD

**Issue by tibolelievre** [assurance-maladie-digital/design-system#2382]
## Description

Il y a un espace sous le FooterBar, qui n'était pas présent avec la version 2.4.0

## Comment reproduire

1. Initialiser un projet avec : 

`vue create my-project --preset assurance-maladie-digital/vue-cli-preset`

2. Lancer le serveur et consulter le footer dans l'ihm, il y a un espace sous celui-ci.

## Comportement attendu

Pas d'espace superflu autour du footer

## Captures d'écran

J'ai modifié la couleur du footer pour mieux voir le soucis

2.4.0

![image](https://user-images.githubusercontent.com/118187347/201673968-5816f852-c0d6-4a44-a548-21f99504b765.png)

2.7.1

![image](https://user-images.githubusercontent.com/118187347/201674121-8a6daadf-99ee-4100-8776-a2733298a4c6.png)

## Environnement

- Navigateur : Firefox 106.0.3

## Priorisation

- Peu prioritaire 

## Projet

Compte ameli web

## Contacts

Thibaut LELIEVRE - Tech Lead

**Comment by deraw** [comment]
Publié dans la version [2.8.0](https://github.com/assurance-maladie-digital/design-system/releases/tag/v2.8.0).
