### ISSUE TITLE
⬆️ Update Errorpage

### ISSUE THREAD

**Issue by Becqueva** [assurance-maladie-digital/design-system#2384]
Mettre à jour la page d'erreur (cf. maquette Figma : [Template](https://www.figma.com/file/gKaLp1f8pMdaf1jcu2mX5R/Design-System-Cnam---Composants?node-id=515%3A67))

RG : 
- La page doit respecter graphiquement la maquette.
- Il doit y avoir "obligatoirement" un bouton de redirection (ne pas laisser la possibilité de le retirer : bonne pratique UX).

**Comment by deraw** [comment]
Le choix de l'illustration à afficher est fait aléatoirement.

D'un point de vue technique :
- On créé un nouveau template `NotFoundPage` pour la page 404
- On créé un nouveau template `MaintenancePage` pour la page de maintenance

De cette façon le composant `ErrorPage` n'est pas modifié, il n'y a donc pas de soucis de rétrocompatibilité, et ce composant peut toujours être utilisé pour des pages d'erreurs différentes

**Comment by francoiscoue** [comment]
Plutot qu'un choix aléatoire de l'image, je propose d'assigner l'image stéthoscope à la page Maintenance et l'image boite vide à NotFoundPage.
