### ISSUE TITLE
Implementation du letter-spacing

### ISSUE THREAD

**Issue by tibolelievre** [assurance-maladie-digital/design-system#2485]
## Description

Le letter-spacing implémenté dans vue-dot n'est pas le même que celui utilisé dans le DS de figma.

Dans figma c'est un pourcentage alors que dans vue-dot cela semble être des pixels.

Par exemple pour le H2 :

- dans figma : 1.5% soit 0.015rem
- dans vue-dot : 1.5 px soit 0.094rem (je suppose 16 * 0.094 = 1.5 px)

Cela fait un rendu différent entre la maquette et l'implémentation (par ex : passage à la ligne différent)

## Comportement attendu

Avoir le même rendu entre la maquette et l'implémentation

## Priorisation

- Peu prioritaire 

## Projet

Compte AS Refonte

## Contacts

[Thibaut LELIEVRE : Tech Lead](thibaut.lelievre@assurance-maladie.fr)

**Comment by Becqueva** [comment]
To do - réu dév + designer puis mise en place de la solution

**Comment by deraw** [comment]
Publié dans la version [v2.9.0-beta.0](https://github.com/assurance-maladie-digital/design-system/releases/tag/v2.9.0-beta.0).
