### ISSUE TITLE
NirField update

### ISSUE THREAD

**Issue by DavidFyon** [assurance-maladie-digital/design-system#2493]
![217034580-3a525fb1-7ece-4dc7-98a9-1451ae34e9d5.png](https://images.zenhubusercontent.com/5a0daa448a75884b9087b1ab/f4064d11-0583-484d-8fba-2de878584564)

**Comment by DavidFyon** [comment]
@Becqueva possible d'avoir des specs fonctionnelles ?
Ex : la clé est-elle obligatoire, son champs doit-il s'afficher par défaut...

**Comment by Becqueva** [comment]
Ajouter un * en cas de champ obligatoire (demande compte entreprise)
