### ISSUE TITLE
Header complexe

### ISSUE THREAD

**Issue by christopheGaon** [assurance-maladie-digital/design-system#2508]
## Description

Header Complexe avec plus d options
avoir aussi un mode simple du Header pour le P1

terminer :
- j ai un figma validé du header v2 (Dicom ok sur ca)
- Alexis deny est ok pour utiliser dans le compte as P1 en version light
- Les devs ont fait une étude d impact sur le code du composant Header actuel

## Priorisation

- Très prioritaire

## Projet

Projet P1
## Contacts

@alexis Denis du P1 a ramener sur le github

**Comment by deraw** [comment]
Ce sujet ne sera pas intégré dans la v2, il pourra être retravaillé ultérieurement dans la v3.
