### ISSUE TITLE
Ajouter une balise meta description par défaut dans le Starter Kit

### ISSUE THREAD

**Issue by christopheGaon** [assurance-maladie-digital/design-system#2511]
## Type

- Étude

## Description

Analyse sur la balise meta a partir de vue-meta.
Voir comment la remonter pour des raison d amelioration seo

**Comment by Becqueva** [comment]
Manque des précisions pour estimation

**Comment by deraw** [comment]
Après revue, l'expert SEO nous déconseille d'avoir une balise meta description qui a contenu mis à jour.
