### ISSUE TITLE
FIGMA | Period picker

### ISSUE THREAD

**Issue by Becqueva** [assurance-maladie-digital/design-system#2512]
En tant qu'utilisateur du DS je veux pouvoir intégrer un datepicker incluant la possibilité de saisir une période. 

Contraintes :
(1) La cellule d'input doit être, en matière de formalisme, identique au datepicker
- Elle doit donc être de style outlined
- Les messages d'erreur ou d'informations complémentaires doivent respecter les standards du DS

(2) Le format doit être indiqué dans le label d'input et non en hint pour garantir l'accessibilité du composant

(3) L'affichage du volet calendrier doit respecter le formalisme de celui du datepicker
 
Critères d'acceptabilité :
(1) Le hover respecte les standards du DS

(2) L'état selected respecte les standards du DS

(3) Le composant est intégrable dans le composant filtre (complexe ou v2)

**Comment by deraw** [comment]
Cette fonctionnalité est déjà présente sous plusieurs formes en v2, on pourra retravailler le sujet plus tard dans la v3.
