### ISSUE TITLE
Améliorer l'accessibilité des hint sur les composants Input

### ISSUE THREAD

**Issue by Becqueva** [assurance-maladie-digital/design-system#2515]
Le Design System doit garantir que l'utilisation des composants input respectent les critères de l'accessibilité RGAA.

Il est demandé aux développeurs d'étudier si l'utilisation du hint (dédié aux messages complémentaires type "format attendu") respecte l'accessibilité.

Cette US doit être croisée avec l'US #2514 Audit de l'accessibilité du DS

**Comment by DavidFyon** [comment]
Je pense que la solution n'est pas de mettre les infos du hint dans le placeholder comme évoqué précédement mais de bien utiliser les balises d'accessibilité aria type aria-labelledby, aria-describedby... sur les champs VInput, VTextField...

**Comment by deraw** [comment]
https://github.com/vuetifyjs/vuetify/issues/16467

**Comment by deraw** [comment]
Je pense qu'il faut faire une PR sur Vuetify directement pour accélérer la résolution de ce ticket 👀

**Comment by deraw** [comment]
https://github.com/vuetifyjs/vuetify/pull/17448
