### ISSUE TITLE
Ajouter le logo du compte ameli au Design System

### ISSUE THREAD

**Issue by AlexisDENY** [assurance-maladie-digital/design-system#2526]
## Description

Nous souhaiterions intégrer le logotype du compte ameli dans le Design System afin de participer à l'effort de mise en commun des éléments.

## Pièces jointes

4 variantes du logo sont à noter : 

- Le logo classique
![Logo compte ameli classique](https://user-images.githubusercontent.com/111863355/218742377-f7235145-2175-42c4-a722-bb590a58063b.svg)

- Le logo version mobile
![Logo compte ameli mobile](https://user-images.githubusercontent.com/111863355/218744214-9b9a3aee-b4c0-43bf-a32b-1244572ce6e3.svg)

- Le logo version "header réduit" classique
![Logo compte ameli réduit classique](https://user-images.githubusercontent.com/111863355/218745684-f2cf1def-7904-474b-a922-58f69f11f9de.svg)

- Le logo version "header réduit" mobile
![Logo compte ameli réduit mobile](https://user-images.githubusercontent.com/111863355/218747458-bebcdd14-5091-4cb8-b94b-7959d17e83cc.svg)

## Priorisation

- Prioritaire

## Projet

Compte ameli assuré (P1)

## Contacts

Alexis DENY : alexis.deny@assurance-maladie.fr

**Comment by deraw** [comment]
Publié dans la version [v2.9.0](https://github.com/assurance-maladie-digital/design-system/releases/tag/v2.9.0).
