### ISSUE TITLE
Ajouter le mode sticky au composant HeaderBar

### ISSUE THREAD

**Issue by AlexisDENY** [assurance-maladie-digital/design-system#2527]
## Description

Nous souhaiterions mettre en commun nos besoins de header afin d'intégrer les nouvelles possibilités qu'offrent la charte graphique mis à jour.

Le but est d'intégrer un header "sticky" avec un logotype ancré à gauche, deux boutons ferrés à droite et une possibilité de header réduit au scroll vers le bas. Le retour au header "classique" serait possible au scroll vers le haut.

## Pièces jointes

Ci-joint mon fichier de travail : https://www.figma.com/file/72xvRtwpZcNfLjV43Bddns/Logo-AM?node-id=0%3A1&t=lFQNv5quxcJmhefV-1
Vous trouverez des suggestions d'animations en mode présentation sur les frames "Logo AM" (Flow1) et "Logo desktop anim" (Flow 2).

## Priorisation

- Peu prioritaire 

## Projet

Compte ameli assuré (P1)

## Contacts

Alexis DENY : alexis.deny@assurance-maladie.fr

**Comment by christopheGaon** [comment]
1. separer les deux pr logo ameli et mode sticky
2. composant logo sacrement modifié
