### ISSUE TITLE
Améliorer l'accessibilité des couleurs

### ISSUE THREAD

**Issue by AlexisDENY** [assurance-maladie-digital/design-system#2528]
## Description

Nous aimerions améliorer l'accessibilité sur le Design System afin de respecter les obligations dans ce domaine pour un outil tel que le compte ameli assuré (P1).
Nous avons remarqué que certains composants étaient "colorisés" en gris pas effet de transparence sur une couleur noire. C'est assez difficile de tester l'accessibilité sur ces éléments et la couleur de "rendu" ne l'est finalement pas (exemple ci-dessous avec une "teinte de gris" qui est du noir avec 38% d'opacité, couleur rendue #9E9E9E non-accessible sur un fond blanc).

Piste de réflexion : ne plus utiliser l'opacité pour les éléments graphiques signifiants et choisir des contrastes conformes au RGAA en vigueur.

## Comment reproduire

1. (https://digital-design-system.netlify.app/composants/formulaires/form-field)
2. Inspecter
3. chercher la couleur fieldset

## Comportement attendu

Couleur permettant un contraste accessible

## Captures d'écran

![Annotation 2023-02-14 143404](https://user-images.githubusercontent.com/111863355/218753756-2c29b4ee-4b03-49a4-a98f-1e45043d0018.png)

![Annotation 2023-02-14 143405](https://user-images.githubusercontent.com/111863355/218753911-9821f22d-7104-47b2-90f8-05c59b987fcc.png)

## Environnement

- Navigateur : TOUS

## Priorisation

- Très prioritaire

## Projet

Compte ameli assuré (P1)

## Contacts

Alexis DENY : alexis.deny@assurance-maladie.fr

## Commentaires 

Peut-être vérifier que cela ne concerne que les inputs et que rien d'autre n'est atteint par ce sujet de contraste.

**Comment by deraw** [comment]
Bonjour,

Les couleurs transparentes sont bien accessibles et conformes au WCAG (mêmes critères que dans le RGAA), nous avons vérifié avec cet outil https://contrast-ratio.com/#rgba%280%2C0%2C0%2C.87%29-on-white

**Comment by deraw** [comment]
> Bonjour @deraw , Dans l'exemple cité, la couleur du cadre fieldset est rgba(0,0,0,.38) et non rgba(0,0,0,.87) : https://contrast-ratio.com/#rgba%280%2C0%2C0%2C.38%29-on-white

Le cadre n'est pas concerné par les règles d'accessibilité car c'est un élément décoratif. Par contre je me suis bien trompé de valeur, c'est `rgba(0,0,0, .6)` mais cela reste tout à fait accessible

**Comment by AlexisDENY** [comment]
> > Bonjour @deraw , Dans l'exemple cité, la couleur du cadre fieldset est rgba(0,0,0,.38) et non rgba(0,0,0,.87) : https://contrast-ratio.com/#rgba%280%2C0%2C0%2C.38%29-on-white
> 
> Le cadre n'est pas concerné par les règles d'accessibilité car c'est un élément décoratif. Par contre je me suis bien trompé de valeur, c'est `rgba(0,0,0, .6)` mais cela reste tout à fait accessible

Je ne suis pas d'accord, selon le critère https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#3.3 La zone de saisie (et donc son cadre) est bien un composant d'interface signifiant. 

La valeur rgba(0,0,0,.6) est celle du label, non du cadre. J'en veux pour preuve les captures d'écran ci-dessous. La désactivation de la couleur rgba(0,0,0,.38) dans le code change bien la couleur du cadre qui repasse en rgba(0,0,0,.8).
![Couleur cadre modifié](https://user-images.githubusercontent.com/111863355/225249705-a5145610-2150-4316-9838-a48844f78c03.png)
![Couleur cadre natif](https://user-images.githubusercontent.com/111863355/225249711-51f8a853-cbda-4580-8ba4-c2abbda201ff.png)
![Couleur label](https://user-images.githubusercontent.com/111863355/225249713-53c00637-b7d0-46e4-8700-d6bf492a1455.png)

Je suis désolé d'être tatillon mais nous avons eu des informations de la DINUM qui nous indiquent que les contrôles et les sanctions pour un défaut d'accessibilité vont être mises en place rapidement.

Je reste à dispo pour échanger sur le sujet.

**Comment by deraw** [comment]
@AlexisDENY pas de soucis sur le fait d'être tatillon, on est là pour ça 😄 

En effet c'est bien un soucis puisque la bordure permet d'identifier le composant. Nous allons le corriger, si besoin de le faire chez vous en urgence vous pouvez ajouter ce code en attendant le correctif :
```scss
// Fix fieldset border color
.theme--light.v-text-field--outlined:not(.v-input--is-focused):not(.v-input--has-state) {
	> .v-input__control > .v-input__slot fieldset {
		color: rgba(0, 0, 0, .42) !important;
	}
}
```

**Comment by deraw** [comment]
Publié dans la version [v2.9.0](https://github.com/assurance-maladie-digital/design-system/releases/tag/v2.9.0).
