### ISSUE TITLE
Ajouter un message d'erreur sur retour du Rating Picker

### ISSUE THREAD

**Issue by Sandrine49** [assurance-maladie-digital/design-system#2529]
## Description

A l'identique des messages de confirmation "Merci pour votre réponse." ou "Merci pour vos remarques utiles à l'amélioration du site.", est-ce possible de prévoir un message d'erreur lorsque que l'enregistrement de l'avis n'est pas possible à cause d'un pb technique (retour back API KO) ? 
Cela permettra d'informer l'utilisateur que son avis n'a pas pu être transmis.

## Pièces jointes

Exemple de message : 
![exempleMessageRetourKORatingPicker](https://user-images.githubusercontent.com/120463428/218816144-cd7ae0ce-add8-4aa8-8162-f053b21ac0ab.jpg)

## Priorisation

- Prioritaire

## Projet

Compte ameli web assuré (P1)

## Contacts

Sandrine (PPO) : sandrine.chabirand@assurance-maladie.fr
Thibaut (Tech Lead) : thibaut.lelievre@assurance-maladie.fr

**Comment by deraw** [comment]
Bonjour,
Ce message ne peut pas faire partie du composant avis et doit être intégré dans l'application car c'est un message technique lié à l'application.
Cordialement
