### ISSUE TITLE
Rating Picker  > Modale mode

### ISSUE THREAD

**Issue by DavidFyon** [assurance-maladie-digital/design-system#2550]

**Comment by Sandrine49** [comment]
On souhaite avoir la possibilité d'afficher le bloc "Pouvez-vous nous en dire plus ?" dans une modale (écran 2 ci dessous) lorsque l'utilisateur aura au préalable sélectionné le smiley "Pas du tout" (écran 1 ci dessous) afin d'obtenir le maximum de retour utilisateur.

**_1 - Choix du smiley "Pas du tout" :_** 
![Ecran1-choixSmileyPasDuTout](https://user-images.githubusercontent.com/120463428/222212612-cce41859-cb81-4505-85ea-113c8a4edd61.jpg)

**_2 - Affichage du bloc "Pouvez-vous nous en dire plus ? avec la liste des réponses dans une modale :_** 
![Ecran2-choixReponsesDansModale](https://user-images.githubusercontent.com/120463428/222212636-3d03c7b9-cd2d-4eda-a939-efbc9e5b950c.jpg)

**_3 - Après clique sur "Transmettre mon avis" retour sur la page initiale avec affichage des réponses sélectionnées : (pour info car hors périmètre de cette issue)_**
![Ecran3-affichageRemerciementRatingPicker](https://user-images.githubusercontent.com/120463428/222212668-e804d4f0-7b8a-4e41-a781-2f5e553908a5.jpg)
