### ISSUE TITLE
Corriger l'incohérence entre les couleurs du Figma et l'implémentation

### ISSUE THREAD

**Issue by tibolelievre** [assurance-maladie-digital/design-system#2552]
## Description

Il y a des divergences de couleurs entre le figma du DS et l'implémentation vue.

Par exemple le secondary est cyan darken 40 dans le DS et cyan.darken20 dans l'implémentation

## Reproduction minimale

Dans vue-dot : 

![image](https://user-images.githubusercontent.com/118187347/221834468-47f921d2-59a8-4f31-8b92-cbaee2bd757d.png)

## Comportement attendu

Dans Figma : 

![image](https://user-images.githubusercontent.com/118187347/221834567-6f84f8ef-00fe-40c6-bdb0-a950da6d6dd1.png)

## Priorisation

- Prioritaire

## Projet

Compte AS Refonte

## Contacts

Thibaut LELIEVRE - Tech Lead

**Comment by deraw** [comment]
Publié dans la version [v2.9.0](https://github.com/assurance-maladie-digital/design-system/releases/tag/v2.9.0).
