### ISSUE TITLE
Ajouter le composant ContextualMenu

### ISSUE THREAD

**Issue by Julien-Baylac** [assurance-maladie-digital/design-system#2571]
Ajouter le composant ContextualMenu
Figma : https://www.figma.com/file/gKaLp1f8pMdaf1jcu2mX5R/DS-CNAM---WIP-Composants?node-id=551%3A8001&t=EfHMOKb3cIktq1T1-1

**Comment by christopheGaon** [comment]
RatingPicker dans la classe ContextualMenu
Peux t on utilise le navigationDrawer comme base de cette pr ou pas , @deraw @Becqueva a revoir ensemble

**Comment by Becqueva** [comment]
![Image](https://user-images.githubusercontent.com/86305670/229131925-259266f4-76ef-4021-bdc2-12b9b3c3317c.png)
