### ISSUE TITLE
Refactoriser le RatingPicker

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#2593]
Ajouter un slot de contenu pour supprimer la partie formulaire intégrée au composant et la laisser à la main du projet dans le but de simplifier l'utilisation et la maintenance du composant.

**Comment by Julien-Baylac** [comment]
- [ ] Utiliser VAlert pour le bouton valider
- [ ] Adapter : MultipleAnswers
- [ ] Ajouter les v-model
- [ ] Utiliser un label plutot qu'un titre
- [ ] Faire le menage dans les props
- [ ] Bloquer text area apres validation
- [ ] Vérifier si le formfield peut être utilisé dans le multipleAnswers

**Comment by christopheGaon** [comment]
rebase la mr  https://github.com/assurance-maladie-digital/design-system/pull/2656 sur celle de https://github.com/assurance-maladie-digital/design-system/pull/2653 @DavidFyon 

finir la mr https://github.com/assurance-maladie-digital/design-system/pull/2659 chris
ajouter les tests sur les mixins 100%
reporter la fonctionnalité choix au clavier dans la mixin ? chris

**Comment by christopheGaon** [comment]
finir la gestion du texte au roll over dans le starPicker
finir la gestion du texte sous les icones 1 et 10 dans le NumberPicker
rebase avec Emotion done
qual done
tests a confirmer la couverture

doc a revoir si review ok
