### ISSUE TITLE
Ajouter la règle de validation matchPatternFn

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#2608]
Ajouter la règle de validation `matchPatternFn`, déjà présente dans le projet Refonte Adher en interne.

**Comment by christopheGaon** [comment]
[adher-ihm-front-develop-src-rules-matchPattern.zip](https://github.com/assurance-maladie-digital/design-system/files/11650816/adher-ihm-front-develop-src-rules-matchPattern.zip)
