### ISSUE TITLE
Clarifier l'utilisation du FormBuilder

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#2615]
Expliquer dans quels cas utiliser les composants du FormBuilder (utilisation avec un formulaire sous forme de JSON ou avec le bundle PHP `questionnaire-bundle` uniquement car certaines fonctionnalités ne sont pas implémentées comme la validation côté client), et indiquer d'utiliser les composants de formulaire de Vuetify dans les cas où il n'est pas recommandé d'utiliser le FormBuilder.

**Comment by Becqueva** [comment]
Déplacer les composants "Formbuilder" "FormList" et "FormItem" de Composant vers Composants techniques

**Comment by DavidFyon** [comment]
"Formulaires" plutôt que "Questionnaires"
