### ISSUE TITLE
Ajouter la prop mobile-version au composant UserMenuBtn

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#2616]
Ajouter la prop `mobile-version` au composant `UserMenuBtn` afin d'adapter le composant plus facilement. Voir avec la team @assurance-maladie-digital/design quelles adaptations sont à faire.

Mettre également à jour l'exemple "Slot par défaut" de la page de documentation du composant HeaderBar qui utilise ce composant afin que l'exemple se comporte mieux sur mobile.

**Comment by Becqueva** [comment]
Non c'est bon, pas de maquette spécifique à associer (usage du datalist dans la navigation mobile)
