### ISSUE TITLE
Permettre la personnalisation du thème dans le composant HeaderBar

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#2617]
Permettre la personnalisation du titre, du sous-titre et de la barre de séparation dans le composant `HeaderBar`, à la manière d'un thème, afin de permettre l'utilisation du composant en suivant la charte graphique sans avoir à intégrer tous les thèmes possibles.

**Comment by christopheGaon** [comment]
peut on avoir un exemple de cette customisation pour voir comment on le met en place

**Comment by deraw** [comment]
Exemple de personnalisation sur le service pharmacies de garde : https://pharmacie-de-garde.ameli.fr/

**Comment by chaapai** [comment]
Serait-il possible d'avoir un exemple de surcharge du menu (pour ajouter une image, mettre en place un dropdown menu, ...) ?

```
<HeaderBar
	:service-title="$t('components.layout.appHeader.title')"
	:service-sub-title="$t('components.layout.appHeader.subTitle')"
	:navigation-items="navigationItems"
>
	<template #navigation-bar-content>
		<div
			v-for="(navigationItem, index) in navigationItems"
			:key="index"
		>
			<!-- Qu'est ce que je fais ici ? -->
		</div>
	</template>
</HeaderBar>
```

**Comment by deraw** [comment]
@chaapai Il y a déjà un exemple sur le slot `default` et un exemple avec le slot `navigation-bar-content` dans la section [personnalisation](https://digital-design-system.netlify.app/composants/structure/header-bar/#section/personnalisation)

Pour la question dans le code que tu envoies, eh bien ça dépend de ce que tu veux faire ! Le slot te permet de modifier le contenu de la barre de navigation, à toi de mettre ce que tu veux dedans
