### ISSUE TITLE
Possibilité d'enlever l'ombre du composant HeaderBar

### ISSUE THREAD

**Issue by oc8** [assurance-maladie-digital/design-system#2663]
## Description
Ajouter la possibilité d'enlever l'ombre du composant HeaderBar.

## Pièces jointes
![Screenshot 2023-03-27 at 11 35 35](https://user-images.githubusercontent.com/46847941/227903230-371f357f-52f3-4f74-bec9-9e0a952a563f.png)

## Projet
Refonte ETET

**Comment by deraw** [comment]
Hello @oc8 

Techniquement c'est déjà possible en utilisant la prop [`vuetify-options`](https://digital-design-system.netlify.app/composants/structure/header-bar/#section/personnalisation), mais je me demande si dans ton cas ça ne serait pas mieux de modifier le `z-index` de la section en dessous du `HeaderBar` afin qu'elle passe au-dessus de celui-ci.
