### ISSUE TITLE
Possibilité de modifier le HeaderMenuBtn

### ISSUE THREAD

**Issue by oc8** [assurance-maladie-digital/design-system#2686]
## Description
Ajouter la possibilité de modifier le HeaderMenuBtn

## Pièces jointes
<img width="444" alt="Screenshot 2023-04-05 at 16 35 55" src="https://user-images.githubusercontent.com/46847941/230114788-28a3703a-ca98-44d7-b761-ad812df17b46.png">

## Projet
ETET

**Comment by deraw** [comment]
Hello @oc8,

C'est déjà possible avec la prop `vuetify-options` et du CSS pour masquer le texte :

```vue
<template>
	<HeaderBar
		:vuetify-options="vuetifyOptions"
		:navigation-items="navigationItems"
		service-title="Étudiants étrangers"
		mobile-version
	/>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	import { NavigationItem } from '@cnamts/vue-dot/src/patterns/HeaderBar/types';

	@Component
	export default class Playground extends Vue {
		vuetifyOptions = {
			menuBtn: {
				btn: {
					icon: true,
					width: 'auto'
				},
				icon: {
					color: 'primary',
					size: '42px'
				}
			}
		};

		navigationItems: NavigationItem[] = [
			{
				label: 'Accueil'
			},
			{
				label: 'Mes projets'
			},
			{
				label: 'Mes outils'
			}
		];
	}
</script>

<style lang="scss" scoped>
	// Hide text in HeaderMenuBtn
	.vd-header-bar-container :deep(.vd-header-menu-btn) {
		font-size: 0;
	}
</style>
```

On pourrait ajouter un slot pour permettre de remplacer le bouton, mais on perdrait les fonctionnalités d'accessibilité du bouton.

**Comment by oc8** [comment]
Merci !
Est-ce qu'il y a une doc pour les objets comme VBtn de vuetify-options ?

**Comment by deraw** [comment]
@oc8 Oui, dans la [section API](https://digital-design-system.netlify.app/composants/structure/header-bar/#section/api) des composants il y a le détail des composants qui peuvent être modifiés via la prop `vuetify-options`

**Comment by oc8** [comment]
Oui, mais comment connaitre leurs propriétés ?
Comme pour l'exemple:
```ts
btn: {
	icon: true,
	width: 'auto'
},
icon: {
	color: 'primary',
	size: '42px'
}
```

**Comment by deraw** [comment]
En fait tu peux appliquer les mêmes props que sur les composants Vuetify `VBtn` et `VIcon`
