### ISSUE TITLE
Ajouter des slots au composant HeaderBar

### ISSUE THREAD

**Issue by oc8** [assurance-maladie-digital/design-system#2702]
## Description
Ajouter le slot `navigation-drawer-seconday-content` au composant HeaderBar, pour pouvoir ajouter des composants spécifiques au-dessus des routes. 

## Pièces jointes
<img width="383" alt="Screenshot 2023-04-12 at 12 25 12" src="https://user-images.githubusercontent.com/46847941/231431774-7e6535c1-9f92-473c-80b8-79aec363b518.png">

## Projet
ETET

**Comment by deraw** [comment]
Après revue avec @Becqueva, on ajoute deux nouveaux slots : `navigation-drawer-content-prepend` et `navigation-drawer-content-append` pour ajouter du contenu avant et après les liens de navigation.

**Comment by DavidFyon** [comment]
Est-ce que ça ne serait pas plus cohérent d'avoir juste un slot `navigation-drawer-secondary-content` qui se comporte comme sur la navigation en mode desktop :

![Image](https://user-images.githubusercontent.com/1822420/233040767-80ee2afc-8d01-4f8d-9c74-ec3b36dc8d8c.png)

![Image](https://user-images.githubusercontent.com/1822420/233040804-22a4f46e-dfa8-4c43-989e-d8a2589bb087.png)

En terme d'UX ça me parait pas top de mettre la nav secondaire au même niveau que la nav principale (comme sur la maquette).

**Comment by Becqueva** [comment]
Vu avec @deraw mardi et @DavidFyon jeudi

**Comment by Becqueva** [comment]
<img width="241" alt="Capture d’écran 2023-04-20 à 17 02 17" src="https://user-images.githubusercontent.com/86305670/233407140-37ce82cb-5c0f-47c8-ba5e-8db6f393215f.png">

**Comment by Becqueva** [comment]
Impact maquettes
