### ISSUE TITLE
Tooltip background : retour sur la transparence

### ISSUE THREAD

**Issue by AlexisDENY** [assurance-maladie-digital/design-system#2753]
## Description

Le tooltip ouvert possède un texte sur un fond de couleur sombre mais pas opaque, ce qui laisse entrevoir ce qu'il y a derrière l'objet. Cela peut être perturbant (même si accessible au niveau des contrastes) à la lecture.

## Comportement attendu

Opacifier le background ajouterait du confort de lecture.

## Captures d'écran

![image](https://user-images.githubusercontent.com/111863355/234272469-92cb67d7-b7e1-4237-921c-dab7de45ec73.png)

## Priorisation

- Peu prioritaire 

## Projet

Compte ameli assuré - Programme 1

## Contacts

Alexis DENY
alexis.deny@assurance-maladie.fr

## Commentaires 

Vu avec Valentin Becquet

**Comment by deraw** [comment]
@Becqueva @DavidFyon il faut qu'on en discute ensemble mardi

**Comment by deraw** [comment]
La modification a été effectuée côté Figma pour correspondre à la version actuelle qui est plus opaque
