### ISSUE TITLE
Vérifier si la fonction html est toujours nécessaire

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#2772]
Dans les test unitaires, une fonction `html` a été ajoutée comme correctif pour ne pas inclure le code source des fonctions dans les snapshots.

Depuis, cela semble avoir été corrigé. Si c'est bien le cas, on peut marquer cette fonction comme étant dépréciée dans le commentaire JS Doc et dans la documentation.
Et on pourra supprimer le `TODO: check if still required`

**Comment by DavidFyon** [comment]
C'est bien le cas, est-ce qu'on supprime les fonctions html() dans les composants du coup ?
