### ISSUE TITLE
Changer police du component NotFoundPage comme sur la maquette

### ISSUE THREAD

**Issue by Jeremy-CNAM** [assurance-maladie-digital/design-system#2785]
## Description

La police du '404' du composant ErrorNotFound n'est pas la même dans le DS(Version 2.9.0) que dans les maquettes Figma.

## Comportement attendu

Avoir la même font que dans la maquette:

Screenshot de la font dans la maquette Figma:
![image](https://user-images.githubusercontent.com/132574184/236203337-6ef7b931-0af4-448f-b0fc-2d027be7d393.png)

## Captures d'écran

Composant dans la maquette:
![image](https://user-images.githubusercontent.com/132574184/236201115-9f9781a3-956e-4654-bde1-f3591358e0f3.png)

Composant dans le DS(Version 2.9.0):
![image](https://user-images.githubusercontent.com/132574184/236201519-853358c6-456f-40bc-89ca-59c99bd54a7c.png)

## Priorisation

- Prioritaire

## Projet

CompteAS Refonte

## Contacts

Joesph Tabet - UI designer : joseph.tabet@inetum.com
Thibaut Lelièvre - TechLead : thibaut.lelievre@assurance-maladie.fr
Jérémy Lamy - dev front : jeremy.lamy.ext@inetum.com

**Comment by Becqueva** [comment]
Correction de la font dans Figma (on laisse ce qui est implémenté)

**Comment by Becqueva** [comment]
Maquette mise à jour par rapport à ce qui est développé. Ne pas faire de modif dans vuedot - livraison du figma en cours donc voir sur la nouvelle version 2.9
