### ISSUE TITLE
Les templates : est-ce qu'un seul ne pourrait pas suffire ?

### ISSUE THREAD

**Issue by tibolelievre** [assurance-maladie-digital/design-system#2826]
## Description

Ceci est une réflexion et non un bug. Il y a trois templates qui se ressemblent : MaintenancePage, ErrorPage et NotFoundPage.

Est-ce qu'un seul template ne pourrait pas suffire ?

Je pense que le NotFoundPage permet de tout faire, mais peut-être revoir son nom.

## Priorisation

- Peu prioritaire 

## Projet

P1 - Compte AS Refonte

## Contacts

Thibaut LELIEVRE

**Comment by deraw** [comment]
Hello @,
En fait au début il n'y avait que le template `ErrorPage`

**Comment by christopheGaon** [comment]
bonjour @tibolelievre , il faudrait qu'on en discute avec les templates de vos pages d erreurs, pour avoir les differents cas possible. Avec qui je dois voir ca chez vous ?

**Comment by tibolelievre** [comment]
Voici les 3 pages d'erreurs qui ont été demandées par les POs côté refonte : 
![2023-06-05 15_46_02-UI-ameli Web Refonte – Figma — Mozilla Firefox](https://github.com/assurance-maladie-digital/design-system/assets/118187347/797b5560-c870-45d8-be04-231d7d4fa26e)
![2023-06-05 15_46_58-UI-ameli Web Refonte – Figma — Mozilla Firefox](https://github.com/assurance-maladie-digital/design-system/assets/118187347/0405a4d3-7595-4bb7-b050-530e40a384d5)

Petite précision : la page de maintenance sert lorsque l'on ferme une fonctionnalité (pas pour le site complet), d’où la présence du bouton.

Pour notre besoin, le template NotFoundPage permettrait de tout faire si on y ajoute la possibilité de supprimer le code d'erreur.

**Comment by tibolelievre** [comment]
On se pose également la question de la « pertinence » de garder la card en mode mobile.

**Comment by deraw** [comment]
Le template `ErrorPage` a été mis à jour pour répondre aux différents besoins, et les templates `MaintenancePage` et `NotFoundPage` utilisent maintenant ce template également.
