### ISSUE TITLE
Rating Picker issue 

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#2839]
Composant Rating Picker 

Le composant sur Figma dans le DS n'est pas exactement identique a:
https://digital-design-system.netlify.app/composants/feedback/rating-picker/#section/utilisation

- la couleur vert est différente
- le smile Disabled est manquante
- L'icone check-circle est manquante

![3700430C-6944-4C92-9C8E-E2CCB9F5142B_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/a7a876ad-2c22-4071-bf1b-6ad32d3871b1)
![ED5CC717-9892-4EC6-A548-6179C993BA1A_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/a80e6e0b-c4ea-430b-9e51-d95e8531f96a)
![55FB498E-F731-41A7-AD1F-067B39DEC02D](https://github.com/assurance-maladie-digital/design-system/assets/133644194/28a3101e-19ed-41aa-b444-436fee6a4cb2)

**Comment by deraw** [comment]
Hello @JosephTabet, le composant doit être mis à jour sur Figma, le suivi se fait sur le ticket #2797
