### ISSUE TITLE
DS - Figma: Mauvaise couleur Tooltip 

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#2844]
## Description 
Composant Tooltip
La couleur du tooltip publié ds la dernière version du DS de l'équipe de développement ne corresponds pas a celui du DS de Figma

## Comportement attendu
Avoir la bonne couleur tooltip sur Figma

## Captures d'écran
Tooltip du DS de l'équipe de développement :
<img width="958" alt="1C3A0177-1058-4038-A7B5-1BC982A08977" src="https://github.com/assurance-maladie-digital/design-system/assets/133644194/53d6e00b-742e-4d89-ae94-bcef6af2ac1e">

Tooltip du DS de Figma :
![14F95676-5C56-46D2-884A-F6F4A1C5D9CE](https://github.com/assurance-maladie-digital/design-system/assets/133644194/d5d72115-1ef8-411d-998f-17776a5452b6)

## Priorisation

- Prioritaire

## Projet
P1 - Compte AS Refonte

## Contacts

Joseph tabet  UI-Designer joseph.tabet@inetum.com

**Comment by Becqueva** [comment]
Le composant tooltip est un composant vuetify (maquette dans Figma mais non intégré dans vuedot), la couleur est une variable à adapter selon les besoins du produit. Il n'y a pas de couleur définie par le design system. 
Ci-après le guide de respect material sur lequel s'appuie le comportement du composant et les bonnes pratiques UX/UI.
 
https://m3.material.io/components/tooltips/overview
