### ISSUE TITLE
DS - Figma: Selects Composant n'existe pas ds la librarie de figma ds le DS

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#2845]
## Description

Le composant Select n'existe pas ds ma librarie sur Figma, si je veux le sélectionner, je peux le trouver ds Assets mais pas ds la librarie a droite, ni ds input fields ou input ou sélecteurs ...
je pense qu'il y a un probleme ds la nomination , je crée cette issue car ce composant est tres important , il est tres utile ds les maquettes et si il arrivait que vous le modifiez ou l'actualisez, il faudra le modifier manuellement.
Il faut donc l'ajouter ds la librairie ds l'onglet INPUT.

## Comportement attendu

Avoir le composant Selects ds la librarie 

## Captures d'écran

![4FE3B056-C584-4AE7-B412-527991B97A27_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/6e850046-ecb5-4992-94ec-df5630d45ffd)
![E430A469-7BD1-461A-AA91-E0E5C9E54D76_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/8e739602-6913-4fd7-a0af-aae16da4a43a)

## Priorisation

- Très prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph tabet UI-Designer    joseph.tabet@inetum.com

**Comment by Becqueva** [comment]
<img width="1256" alt="Capture d’écran 2023-06-08 à 11 35 52" src="https://github.com/assurance-maladie-digital/design-system/assets/86305670/a58467de-53b5-4286-afa9-e7698e61c9bb">

**Comment by Becqueva** [comment]
@JosephTabet merci de vérifier si le problème est toujours présent ?

**Comment by JosephTabet** [comment]
Je trouve quelle existe ds assets mais pas ds la librairie a droite , ni ds input fields ou input ou sélecteurs ...

**Comment by Becqueva** [comment]
mince, je le vois aussi, est-ce que c'est pas un problème de mise à jour figma ou quelque chose du genre ?

**Comment by Becqueva** [comment]
<img width="411" alt="Capture d’écran 2023-06-08 à 12 03 19" src="https://github.com/assurance-maladie-digital/design-system/assets/86305670/78e488f9-c8cb-4c80-aa77-8e71ae79c111">

**Comment by Becqueva** [comment]
J'espère avoir résolu le problème avec la version 2.10.1 tu me diras si c'est bon ?
