### ISSUE TITLE
DialogBox : Problème vocalisation modal avec titre

### ISSUE THREAD

**Issue by Jeremy-CNAM** [assurance-maladie-digital/design-system#2846]
## Description

Les composants DialogBox ne respectent pas la notice AcceDeWeb https://www.accede-web.com/notices/interface-riche/fenetres-modales/. Lorsqu'une modal a un titre, il faut utiliser aria-labelledby comme décrit dans la notice.

## Comportement attendu

Que la modal suive la notice quant à la vocalisation de son titre.
Exemple décrit dans la notice :

![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/8f8daeda-8ce7-40d3-b3de-4c2f62f99b56)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Sandrine Chabirand - PPO - sandrine.chabirand@assurance-maladie.fr
Thibaut Lelievre - TechLead - thibaut.lelievre@assurance-maladie.fr
Jérémy Lamy - Developpeur front - jeremy.lamy.ext@inetum.com

**Comment by deraw** [comment]
PR ouverte sur Vuetify https://github.com/vuetifyjs/vuetify/issues/14755
