### ISSUE TITLE
Problèmes avec le footer

### ISSUE THREAD

**Issue by SullivanPro** [assurance-maladie-digital/design-system#2851]
## Description

Bonjour,

Dans la documentation du composant **FooterBar** il est indiqué de pouvoir ajouter, modifier différentes liens grâce à la prop `link-items`, mais lorsqu'on l'utilise rien ne change. Après avoir vérifié le code dans le package, cet prop n'est pas présent sur la dernière version stable 2.9.0.

En outre, sur le mode étendu en mode mobile nous avons une flèche qui s'affiche permettant de remonter la page. Nous souhaitons l'obtenir également dans le mode "normal"

## Priorisation

- Prioritaire

## Projet

 DROIT OPPOSITION

## Contacts

Sullivan FABRE - Dev Front
Melissa ROLAS - UX/UI Designer

**Comment by deraw** [comment]
Hello @SullivanPro,
La prop est bien présente et fonctionnelle comme documentée https://digital-design-system.netlify.app/composants/structure/footer-bar#modification-des-liens. S'il y a un problème il faut vérifier que les dépendances et nous fournir une reproduction.

Pour la flèche pour remonter en haut de la page, elle n'est pas présente sur le mode simple et ne sera pas ajoutée, il faut utiliser le mode étendu si vous souhaitez qu'elle soit présente, je vais voir avec les UX/UI pour que les maquettes soient mises à jour en conformités 🙂
