### ISSUE TITLE
Évolution UploadWorkflow : ajouter plusieurs dépôts pour une nature

### ISSUE THREAD

**Issue by Becqueva** [assurance-maladie-digital/design-system#2862]
Le composant actuel ne gère pas le dépôt multiple pour une nature. Cas d'usage : un utilisateur veut déposer un recto et un verso séparé (problème d'assemblage de document) dans la configuration actuelle il ne peut pas. Il doit choisir un document pour un dépôt.

**Comment by christopheGaon** [comment]
Il faudrait pourvoir a une description de ce sujet @Becqueva mais je pense qu il faut renoncer a toute evolution pour se concentrer sur la correction des bug sur la v2 et la mise en place de la v3 plutot.

**Comment by Becqueva** [comment]
C'est un besoin produit (ici ETET). Deux options sont possibles : Faire une évolution du composant côté DS ou aucune évolution côté DS mais création du composant côté produit.

**Comment by Becqueva** [comment]
@christopheGaon

**Comment by christopheGaon** [comment]
Demandons au produit de faire cette evolution dans son produit et ensuite de faire une pr sur le ds , avec notre aide. Ainsi , on ne bloque personne et on enrichi ensuite

**Comment by Becqueva** [comment]
Il a la main pour modifier le composant ? Si oui ok

**Comment by deraw** [comment]
L'évolution n'est pas possible avec le composant actuel en gardant la rétrocompatibilité, ils ont meilleur temps de partir sur un nouveau composant
