### ISSUE TITLE
DS Figma : Ajouter la card dans le composant Figma // DS DEV : Suppression de la bordure de la card en mode mobile

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#2863]
## Description

Pour le Ds Figma:

Le composant sur Figma dans le DS n'est pas exactement identique a:
https://digital-design-system.netlify.app/templates/maintenance-page
Il faut ajouter la cards ... donc il faut que le composant soit avec la cards ds le DS sur Figma

Pour le DS des développeur :
Retirer la bordure de la card lorsqu'un écran est inferieur à 600px.

ATTENTION, cette modification devra sûrement être faite uniquement sur le composant générique lié à cette issue : https://github.com/assurance-maladie-digital/design-system/issues/2826. 
Sinon, sur tous les composants de page d'erreur.

## Captures d'écran

DS Figma
![3CE8AEDC-5389-4375-8AC5-BA4F21E1A100](https://github.com/assurance-maladie-digital/design-system/assets/133644194/7590b050-81b2-49af-8115-7b8dbf08aed1)

digital-design-system.netlify :
![EBD6277A-DDB4-41ED-9D35-17ACBD8AE08B](https://github.com/assurance-maladie-digital/design-system/assets/133644194/e5acc5fb-6b81-4260-b47a-b4559caecec4)

Pour les Dev - il peut pas retirer la cards :
![image-2023-06-07-14-52-33-006](https://github.com/assurance-maladie-digital/design-system/assets/133644194/dd2bd3fc-5670-42ae-ad71-91334239663b)

## Priorisation

- Très prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph tabet UI-Designer / joseph.tabet@inetum.com

**Comment by Becqueva** [comment]
US résolue : Livraison réalisée le 8/06/23 ici : https://www.figma.com/community/file/1248550350545643459

**Comment by Becqueva** [comment]
Partie design de l'issue résolue, pour l'évolution de composant avec la card comme option en mode mobile merci d'ouvrir une nouvelle issue @JosephTabet

**Comment by Becqueva** [comment]
Partie design de l'issue résolue, pour l'évolution de composant avec la card comme option en mode mobile merci d'ouvrir une nouvelle issue @JosephTabet

**Comment by JosephTabet** [comment]
@Becqueva il y a une issue pour l'évolution de composant avec la card comme option en mode mobile sous le lien:
https://github.com/assurance-maladie-digital/design-system/issues/2826
