### ISSUE TITLE
Besoin d'explication concernant BASE_URL et les fichiers public\js\config.js.XXX

### ISSUE THREAD

**Issue by asicfr** [assurance-maladie-digital/design-system#2865]
## Description
Nous avons un besoin d'héberger une ihm avec un **subpath**.
L'ihm sera donc accessible via une url du type :  http://mondomain/**subpath**/...
Est-ce bien avec la variable BASE_URL que l'on peut mettre en place ce subpath ?
Dans le projet généré, comment configurer la variable BASE_URL svp ? 

Autre question, est-il possible d'avoir deux fichiers config.js, un pour le developpement local et un pour la production et que le choix entre les deux soit automatique en fonction du mode de lancement (process.env.NODE_ENV) ?

Merci d'avance.

**Comment by deraw** [comment]
Hello @asicfr,

Pour mettre en place un sous-chemin, il faut configurer `publicPath` et `distPath` dans le fichier `vue.config.js` :
```js
publicPath: '/sms/',
outputDir: 'dist/sms/',
```

Pour ta deuxième question, le fichier `config.js` est celui utilisé dans l'environnement actuel et il est généré à la volée en fonction des environnements.
Par défaut pour le développement, il est généré automatiquement s'il n'est pas déjà créé en utilisant le fichier `config.js.dist`, et pour les environnements distants la génération se fait en utilisant le fichier `config.js.env` en remplaçant les valeurs avec celles définies dans l'environnement.

Du coup il n'est pas possible de choisir parmi deux fichiers en fonction de l'environnement et ce n'est pas une évolution prévue dans cette version de la stack, après rien ne vous empêche de le faire de votre côté et ça sera un sujet pour la nouvelle stack et la nouvelle plateforme.

**Comment by asicfr** [comment]
Bonjour et merci pour les réponses.
Concernant le 1er point, il s'agit de publicPath et distPath  ou   de publicPath et outputDir ?
Merci d'avance.

**Comment by deraw** [comment]
> Bonjour et merci pour les réponses. Concernant le 1er point, il s'agit de publicPath et distPath ou de publicPath et outputDir ? Merci d'avance.

C'est bien `outputDir`, j'ai mis à jour le commentaire

**Comment by asicfr** [comment]
Bonjour,
J'ai appliqué la configuration indiquée (ajout dans le fichier vue.config.js).
Le code source est disponible ici : https://github.com/asicfr/majskvu3.
Puis, j'ai buildé et déployé le contenu du répertoire dist sur un apache avec un virtual host pointant sur le répertoire en question (DocumentRoot C:/DEV/activites/human/majskvu3/dist).
Lorsque j'ouvre le site depuis un navigateur, les liens du menu ne fonctionnent pas, je n'ai pas le subpath configuré.
Je pense qu'il manque une configuration.
Coridalement

**Comment by asicfr** [comment]
J'ai déployé le projet sur Github page pour pouvoir le tester facilement : 
https://asicfr.github.io/sms/
