### ISSUE TITLE
Documentation - Templates card mobile

### ISSUE THREAD

**Issue by Becqueva** [assurance-maladie-digital/design-system#2866]
Les prévisualisations des templates NotFoundPage et MaintenancePace sont inexactes et devraient passer en mode mobile (car breakpoint < 600px) et non en desktop écrasé.

**Comment by DavidFyon** [comment]
Ce n'est pas tout à fait ça, le mode mobile est ok mais c'est lié au template de la doc pour les cas d'usage.

@deraw 
les margins sont écrasés par ce style dans maintenance-page/usage.vue (je suppose que c'est pour ne pas avoir un aperçu trop petit) :
`:deep(.v-card) {
	padding: 24px !important;
	display: flex !important;
	flex-direction: column !important;
}`
de plus le breakpoint mobile n'est pas pris en compte
