### ISSUE TITLE
Revoir margin et polices du composant maintenance page

### ISSUE THREAD

**Issue by Jeremy-CNAM** [assurance-maladie-digital/design-system#2873]
## Description

Le composant maintenance page que nous utilisons pour la page Service indisponible a des problèmes de taille de font et de margin qui ne respectent pas ceux indiqués sur la maquette Figma

## Comportement attendu

Que le composant respecte les maquettes figma

## Captures d'écran

![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/2abbb8fd-bc29-4322-8e30-54c541d184f4)

## Priorisation

- Très prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Jérémy Lamy - Dev Front - jeremy.lamy.ext@inetum.com

## Commentaires 

J'ai mis sur le screen du composant maintenance page, tous les éléments de style qui ne vont pas. L'image est celle du composant en dev mais les valeurs sont celles du figma et elles ne sont pas respectées.

**Comment by christopheGaon** [comment]
sur la page du ds 

https://www.figma.com/file/gKaLp1f8pMdaf1jcu2mX5R/DS-CNAM---WIP-Composants?type=design&node-id=12427-86537&t=BI6xH4bKKZAGvWAK-0

On a ca 

![Image](https://github.com/assurance-maladie-digital/design-system/assets/15378125/795c6aec-7c0a-43f3-9eb0-daf1039ba348)


Tu peux me donner l url du figma que tu as @Jeremy-CNAM 

@Becqueva , il faut pas que les pages ne soient pas dupliquée dans les projets peut etre ?

**Comment by Jeremy-CNAM** [comment]
Les modifications seront effectuées sur les maquettes de ce figma : https://www.figma.com/file/yGykrOWySGuBgBSAqHG81c/UI-ameli-Web-Refonte?type=design&node-id=11088-36224&t=jzR0GvuHstEQtTxJ-0
