### ISSUE TITLE
DS - Figma : Mettre à jour le composant maintenance page et Page non trouvée en se basant sur les 12 colonnes + version tablette

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#2878]
## Description

Mettre à jour les composants maintenance page et Page non trouvée, en se basant sur les 12 colonnes comme indiqué dans les maquettes, le composant maintenance page ou Page non trouvée que nous utilisons sur Figma , ne respecte pas la margin + creer une option en mode Desk et tablette.

## Comportement attendu

Avoir le composant maintenance page et Page non trouvée basé sur les 12 colonnes en mode Desk et tablette

## Captures d'écran

![6640DB0A-8673-41D2-AC31-A014D2611E76](https://github.com/assurance-maladie-digital/design-system/assets/133644194/09a75a70-62d9-4190-898d-0231dc41879e)

![C793D89C-E2DF-42C8-B991-5A254493C4FB](https://github.com/assurance-maladie-digital/design-system/assets/133644194/4572bff1-aefb-4d90-b94e-cb8e1f9338e1)

![7EE4AEB0-3641-4882-B5AC-DB072D343197](https://github.com/assurance-maladie-digital/design-system/assets/133644194/b2b4bb59-fdff-4431-9018-b6b9efe6d90a)

![A582DA7C-4D1C-4778-A003-54255F6FB8FE](https://github.com/assurance-maladie-digital/design-system/assets/133644194/1753b0f1-17ff-4839-b9cf-1b7de4c0c13d)

Ajouter une option pour tablette
![87BD9729-4D80-47B1-9737-F6CBB3551321_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/e6a96a6e-64d6-40c2-bf03-ccc64d964614)

## Priorisation

- Très prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph Tabet - UI Designer - joseph.tabet@inetum.com

**Comment by Becqueva** [comment]
La construction des composants est basée sur le respect des [breakpoints] (https://v2.vuetifyjs.com/en/features/breakpoints/#breakpoint-service). Il existe 2 tailles : mobile (<600px) et desktop (>600px) du coup la notion de grille n'est pas valable ici.
