### ISSUE TITLE
[vue-dot][NotificationBar] Couleur texte sur la notification de type success

### ISSUE THREAD

**Issue by heristop** [assurance-maladie-digital/design-system#2892]
## Description

La mise à jour du design system en 2.9 / 2.10 créé une régression sur la couleur du texte des notifications de type success.

## Comment reproduire

Ajouter un composant NotificationBar et activer une notification de type success.

## Comportement attendu

La couleur du texte avec le thème clair doit être blanc étant donné que le fond est coloré vert.

## Captures d'écran

![image](https://github.com/assurance-maladie-digital/design-system/assets/206870/0e0ff37f-5ebf-4f6f-94ac-f02f896cf882)

## Environnement

- OS : Ubuntu
- Navigateur : Chrome

## Priorisation

- Peu prioritaire 

## Projet

fondinnov-front

## Contacts

Alexandre Mogère / @heristop

## Commentaires 

Fix temporaire en css : 

```
.v-application .v-snack__wrapper.v-sheet {
	color: white !important;
}
```

**Comment by deraw** [comment]
Hello @heristop 

Le texte doit bien être foncé car le composant a été mis à jour pour respecter les contraintes de contraste :

![screenshot-digital-design-system netlify app-2023 06 14-15_57_45](https://github.com/assurance-maladie-digital/design-system/assets/10298932/05a32cf9-1d5f-477a-a7f2-7ef51ee99784)

Vous avez fait des modifications au composant ? Normalement ça devrait se mettre à jour sans soucis

**Comment by deraw** [comment]
J'ai testé dans votre projet en commentant le correctif que tu as mis et je n'arrive pas à reproduire le bug.

Un truc qui vous manque et qui serait bien d'ajouter c'est la configuration variables Vuetify comme ici https://github.com/assurance-maladie-digital/design-system/blob/dev/packages/vue-cli-plugin-vue-dash/generator/template/src/styles/variables.scss, par exemple les styles typographiques ont été mis à jour via ces variables
