### ISSUE TITLE
Option de supprimer les cards en format mobile

### ISSUE THREAD

**Issue by AlexisDENY** [assurance-maladie-digital/design-system#2894]
## Description

Le format mobile peut se passer de cards pour afficher du contenu en corps de page et apparaître moins "complexe" aux yeux des utilisateurs

## Pièces jointes

Exemple :
![Smartphone 320px -  E6 1  - A2D avec C2S et ETM - Choix bénéficiaire](https://github.com/assurance-maladie-digital/design-system/assets/111863355/87b97657-7685-49d1-aeff-3eda353eb99b)

## Priorisation

- Prioritaire

## Projet

P1 : compte ameli assuré

## Contacts

alexis.deny@assurance-maladie.fr

**Comment by deraw** [comment]
Hello @AlexisDENY,

Vous pouvez le faire facilement dans le projet de cette façon : `<VCard :flat="$vuetify.breakpoint.mobile">`.
Ce n'est pas une fonctionnalité que l'on peut implémenter de façon globale car il y aurait des effets de bord et il n'est pas prévu de créer de composant wrapper pour cela.

**Comment by Jeremy-CNAM** [comment]
@deraw Malheureusement non, on ne peut pas utiliser ":flat="$vuetify.breakpoint.mobile"" car à ma connaissance, lorsque l'on implémente les composants notFoundPage et maintenancePage on a n'a pas accès à la balise VCard. On ne peut donc pas lui ajouter la propriété :flat. Si vous pouviez ajouter l'option directement dans MaintenancePage et NotFoundPage ce serait cool :)
