### ISSUE TITLE
DS - Figma: Maintenancepage et NotFoundPage Composant n'existe pas ds la Librarie et Assets de figma

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#2897]
## Description

Le composant Maintenancepage et NotFoundPage je ne peux le trouver ds Assets ni dans la librairie.

## Comportement attendu

Avoir le composant Maintenancepage et NotFoundPage  dans la librarie et Assets

## Captures d'écran

Ni ds la librairie
![F3DC688E-EAC0-4F40-924D-00CC58ECF7B9](https://github.com/assurance-maladie-digital/design-system/assets/133644194/f303bf78-abef-404e-b351-2d0a85dcb0a0)

Ni ds assets
![7A9C9A09-5331-494E-824C-4CBE08287045_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/c2956554-faff-4c94-b2c8-7db87807be2c)

## Priorisation

- Très prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph Tabet UI Designer

**Comment by Becqueva** [comment]
J'espère avoir résolu le problème avec la version 2.10.1 tu me diras si c'est bon ?
