### ISSUE TITLE
Alignement de l'icone v-alert incorrect pour le mode desktop

### ISSUE THREAD

**Issue by tibolelievre** [assurance-maladie-digital/design-system#2911]
## Description

Dans Figma pour le mode desktop, l'icone du v-alert est centré verticalement.

Dans le vue-dot, il est positionné en haut (comme dans vuetify).

## Comportement attendu

Dans Figma :

![image](https://github.com/assurance-maladie-digital/design-system/assets/118187347/165232de-2dbe-493d-9ad8-438af432d102)

## Captures d'écran

Avec vue-dot :

![image](https://github.com/assurance-maladie-digital/design-system/assets/118187347/56d9ee2f-cbc0-475c-8673-1bec5d0dd219)

## Priorisation

- Peu prioritaire 

## Projet

P1 - Compte AS Refonte

## Contacts

thibaut.lelievre@assurance-maladie.fr

**Comment by Becqueva** [comment]
Correction apportée dans la version 2.10.1 Figma
