### ISSUE TITLE
SkipLink

### ISSUE THREAD

**Issue by tibolelievre** [assurance-maladie-digital/design-system#2915]
## Description

Le SkipLink prend le focus lorsque la page est chargée (et est donc affiché)

## Comment reproduire

Créer une application par défaut et ajouter un SkipLink dans le App.vue par exemple. Puis cliquer sur A propos ou Accueil.

Le SkipLink prend le focus lorsque la page est chargée (et est donc affiché)

## Reproduction minimale

		<SkipLink
			target="#contenu"
			label="Aller au contenu principal"
		/>

## Comportement attendu

Lors de l'accès à une page le lien est masqué et n'a pas le focus. Il s'affiche lors de la tabulation.

Voir les exemples de sites sur l'issue https://github.com/assurance-maladie-digital/design-system/issues/2665

## Priorisation

- Peu prioritaire 

## Projet

P1 - Compte AS Refonte

## Contacts

thibaut.lelievre@assurance-maladie.fr

**Comment by DavidFyon** [comment]
J'ai créé une application et ajouté le SkipLink mais je n'ai pas ce soucis :

Code :

![Image](https://github.com/assurance-maladie-digital/design-system/assets/1822420/f3392da7-e970-4153-8cdc-5e68b45496c1)

![Image](https://github.com/assurance-maladie-digital/design-system/assets/1822420/e626373e-e5a6-488d-97e1-8e2ce30697ca)

Démo :

![Image](https://github.com/assurance-maladie-digital/design-system/assets/1822420/c2339007-b6b0-4e44-8db1-a0a8c0864f5e)

**Comment by tibolelievre** [comment]
Le soucis est quand on clique sur les liens "A propos" ou "Accueil", le lien est affiché et à le focus.

**Comment by deraw** [comment]
Le lien doit bien recevoir le focus lors de la navigation, cf. https://vuejs.org/guide/best-practices/accessibility.html#skip-link
Cela dit on peut en effet le masquer et envoyer le focus sur un élément précédent, soit le body soit un span, c'est ce que l'on va faire
