### ISSUE TITLE
Mode sticky et HeaderBar

### ISSUE THREAD

**Issue by tibolelievre** [assurance-maladie-digital/design-system#2917]
## Description

Lorsque l'on active le mode sticky sur le HeaderBar dans une application par défaut, une partie du contenu est masqué

## Comment reproduire

Créer un projet par défaut.

Ajouter la prop sticky sur le HeaderBar dans AppHeader.vue

## Comportement attendu

Le contenu de la page n'est pas masqué.

## Captures d'écran

![image](https://github.com/assurance-maladie-digital/design-system/assets/118187347/d31ce6f9-7afd-48f1-8a36-ddd14c7f1e10)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

thibaut.lelievre@assurance-maladie.fr

## Commentaires 

Lors du point du 20/06/2023, David nous indiquait qu'il fallait ajouter un margin-top sur le contenu, dans ce cas il serait intéressant de le préciser dans la doc.

Cependant, je pense qu'une autre approche serait d'appliquer directement un margin-bottom sur la HeaderBar lorsque le sticky est activé (sur la classe vd-header-bar-container ?).

**Comment by tibolelievre** [comment]
Je pense que le margin-top appliqué doit évoluer avec le scroll pusique la hauteur de vd-header-bar-content est modifiée avec le scroll.

Par exemple en mode desktop, le margin-top appliqué est de 120px à l'initialisation de la page (ce qui correspond au height du vd-header-bar-content). Lorsque l'on scroll, la hauteur de vd-header-bar-content passe à 72px, mais pas le margin-top lui reste à 120px.

**Comment by deraw** [comment]
> Je pense que le margin-top appliqué doit évoluer avec le scroll pusique la hauteur de vd-header-bar-content est modifiée avec le scroll.
> 
> Par exemple en mode desktop, le margin-top appliqué est de 120px à l'initialisation de la page (ce qui correspond au height du vd-header-bar-content). Lorsque l'on scroll, la hauteur de vd-header-bar-content passe à 72px, mais pas le margin-top lui reste à 120px.

Le problème en faisant ça c'est que ça crée un "saut" au niveau du scroll vu que la hauteur de la page est modifiée
