### ISSUE TITLE
Avoir un accès post clôture sur une Issue

### ISSUE THREAD

**Issue by Becqueva** [assurance-maladie-digital/design-system#2918]
En tant qu'utilisateur du DS je veux pouvoir accéder, commenter ou modifier une demande sur une Issue clôturée.

**Comment by deraw** [comment]
Hello il n'y a pas de différence entre une issue ouverte ou clôturée, il faut être connecté à GitHub afin de pouvoir commenter dessus. Nous avons la possibilité de verrouiller les commentaires mais nous ne l'avons jamais fait
