### ISSUE TITLE
Extraire le composant PeriodField

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#2919]
Extraire le champ de formulaire `PeriodField` contenu dans `FormField` dans un nouveau composant du même nom, en utilisant ce nouveau composant dans `period.vue` dans le `FormField` (sans modifier l'utilisation).

La modification que l'on avait évoquée (utiliser la prop `range` du `VDatePicker` de Vuetify) n'est pas à faire car il faudrait modifier le composant `DatePicker`. Elle pourra être faite en v3 lors de la réécriture des composants.

**Comment by Becqueva** [comment]
Impact FIGMA - intégrer Periodfield avec lien vers doc. vuedot
