### ISSUE TITLE
DS Figma  : Composant Rating picker, ajuster la taille en hauteur du message

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#2921]
## Description

Ajuster le hauteur du message en vert dans le composant rating picker, avant c'était 55px et mnt c 88px

## Captures d'écran

![BAB1F722-F740-46A7-AC7A-C169A48E93EC_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/4f969d84-b3aa-4121-b412-42c33a9f35cc)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph Tabet - UI Designer - joseph.tabet@inetum.com

**Comment by Becqueva** [comment]
Résolu et disponible dans la version 2.10.1

**Comment by JosephTabet** [comment]
@Becqueva Jai integré la nouvelle version sur Figma, mais le hauteur n'est pas changé, il a resté 88px, on veut quil soit 55px
en plus le texte mnt n'est pas centré avec l'icone 

![457D1D14-46B6-4B37-8B78-1524AC6CE22E_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/e02df961-2767-4d78-a6e4-522a0628e3df)

![17F1FCF6-25C8-4E96-87EC-A1E153073F97_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/80fddea1-422b-4e75-bebd-bb6988f920a9)
