### ISSUE TITLE
DS Figma : Peut on ajouter le popin dans le composant Rating Picker ?

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#2927]
## Description

Peut on ajouter le popin dans le composant Rating Picker ?

## Captures d'écran

![C8FCEC18-1F6A-416B-A380-E6F45CA2A902](https://github.com/assurance-maladie-digital/design-system/assets/133644194/32015d7b-c8ed-4f5a-b3e7-5ec03d3b37af)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph Tabet - UI Designer - joseph.tabet@inetum.com

**Comment by Becqueva** [comment]
Le design system fourni un ensemble de composant facilitant le développement front des produits digitaux. Il ne peut pas assurer les connexions avec le back et ne peut pas intégrer des éléments de contexte puisque par définition le contexte est propre à chaque produit. Il co-fonctionne avec la librairie vuetify. Comme tout design system il suit la logique de la standardisation pour répondre à une majorité des cas d'usage. Néanmoins il ne peut pas les couvrir "TOUS" c'est pourquoi dans ce cas présent, le composant rating picker comporte une section "slot" pour laisser au produit la main sur la "spécificité" de son usage et l'équipe produit peut décider librement de customiser son fonctionnement si elle estime que son besoin dépasse le cadre du composant initial. Le critère principal de décision pour réaliser une customisation est le suivant : est-ce que la customisation du composant, donc la charge à investir par l'équipe produit, est justifiée par rapport au besoin, donc au gain, qu'elle produit ? Chaque équipe produit possède le dernier mot sur l'intégration d'un composant mais elle doit avoir conscience qu'une customisation implique une charge de maintenance supérieure et que cela réduit les bénéfices d'utilisation d'un design system (accélération de maquettage et d'intégration, respect de la charte graphique, gain en accessibilité, etc.). 

Pour résumé : Oui vous pouvez ajouter une popin mais ce n'est pas l'équipe du DS qui le fera :)
