### ISSUE TITLE
Ds-Figma : Le composant LOGO existe en double ds la librarie de figma

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#2933]
## Description

Il y a un probleme ds la nomination , je crée cette issue car apres chaque integration du DS sur figma
Le logo ds le header il change seul , car il y a double nom pour le meme composant
NB: éviter de supprimer le composant logo ce qui est avec tous les themes 'capture d'écran attacher'

## Comportement attendu

Avoir le composant logo ds la librarie mais pas en double 

## Captures d'écran

![5792CA42-73B6-4702-885F-BFF3BC6B95C0_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/bcd14fd1-0605-4380-8083-dce813361d42)

![5289BAF2-B3F5-4F1B-8990-76DBC25AD3FB](https://github.com/assurance-maladie-digital/design-system/assets/133644194/55e89958-c5e0-4df3-b1fd-b95bb8f95615)

apres l'integration
![4C2A79E2-719F-4DDB-96FC-BC909F8EF03D_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/f1f77695-07cd-4b74-8417-48d8ae8473f0)

avant l'integration
![C7D317AB-40D8-40E7-AD3B-75D56936607D_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/893fc4f9-0f86-4cbc-9e69-be7deb66a947)

tous les themes:
![B3A153A0-50D5-4175-817E-760427B8E73A_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/0cc870d8-44c1-4bf4-92f5-7050a37cd2b2)

## Priorisation

- Très prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph Tabet UI-Designer / joseph.tabet@inetum.com

**Comment by Becqueva** [comment]
Doublon de la liste supprimé
