### ISSUE TITLE
Couleur footer dark différente des maquettes

### ISSUE THREAD

**Issue by Jeremy-CNAM** [assurance-maladie-digital/design-system#2935]
## Description

La couleur du footer dans le composant de dev est différente de celle du composant figma.

Dev : #434647
Figma : #545859

## Comportement attendu

Que la couleur soit celle des maquettes

## Captures d'écran

Couleur du composant en dev:
![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/5e532e8e-a29f-4cf6-bad3-d94afda9e7ef)

Couleur du composant sur figma:
![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/f3f7d7e4-12b1-4fd4-9b33-6e5280aa7ca8)

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Jérémy Lamy - Developpeur front - [jeremy.lamy.ext@inetum.com](mailto:jeremy.lamy.ext@inetum.com)

**Comment by Becqueva** [comment]
Il y un delta en effet, le gris implémenté est le darken-20 alors que celui sur la maquette est le gris de base. Je vais modifier celui de Figma pour la prochaine release pour réduire l'impact côté code. Il n'y a pas de recommandation spécifique côté charte pour une couleur (seule la notion de "foncé" est indiquée cf. image ci-dessous). Rien de bloquant pour vous puisque vous pouvez utiliser le footer de vuedot et utiliser en l'état le footer de FIGMA (il se mettra automatiquement à jour lors de la prochaine release). Impact côté recette proche de zéro.

**Comment by Becqueva** [comment]
<img width="626" alt="Capture d’écran 2023-06-28 à 10 37 15" src="https://github.com/assurance-maladie-digital/design-system/assets/86305670/2838d089-2981-4e2f-b9ed-e3cf2f867133">
