### ISSUE TITLE
DS Figma : Composant Rating picker - ajuster la taille en hauteur du message et centré le message

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#2936]
## Description

Ajuster le hauteur du message en vert dans le composant rating picker a 55px
en plus le texte n'est pas centré avec l'icone

## Captures d'écran

![E32CC172-7F0A-459B-BD37-2831F358BF32](https://github.com/assurance-maladie-digital/design-system/assets/133644194/d2fbb18c-a3c4-468b-9f35-456ef8d21e68)

![17F1FCF6-25C8-4E96-87EC-A1E153073F97_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/22636ecc-c03f-4150-9394-12a8ee07bb7c)

## Priorisation

- Très prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph Tabet - UI Designer - joseph.tabet@inetum.com

**Comment by Becqueva** [comment]
Impact sur le composant Alert (aucun impact sur le master rating picker) - Composant Alert modifié en conséquence
