### ISSUE TITLE
Ajout de la possibilité d'utilisé le DatePicker avec le type month

### ISSUE THREAD

**Issue by DamiloGaston** [assurance-maladie-digital/design-system#2949]
Bonjour,

Nous sommes actuellement intéressés par l'utilisation du type month du VDatePicker original de Vuetify. L'objectif est de pouvoir saisir des périodes entre deux mois en utilisant ce composant.

J'aimerais savoir s'il est envisageable d'apporter cette évolution à votre composant datePicker. Ce serait très utile pour notre cas d'utilisation spécifique.

Merci

Bonne journée

Gaston DAMILO

**Comment by deraw** [comment]
Hello @DamiloGaston,

Nous n'acceptons plus de demandes d'évolution sur la v2 pour que l'on puisse se concentrer sur la v3.

Dylan
