### ISSUE TITLE
Problème structure composant ErrorNotFound en mode tablette

### ISSUE THREAD

**Issue by Jeremy-CNAM** [assurance-maladie-digital/design-system#2954]
## Description

Le composant ErrorNotFound n'a pas le bon comportement en mode tablette (width < 960px). La disposition des éléments est directement comme le mode mobile alors qu'il devrait être, à l'image du composant "MaintenancePage", comme le mode desktop mais en réduit.

## Comment reproduire

Tester le composant avec une fenêtre dont la width est inférieur à 960

## Comportement attendu

Que la disposition des éléments dans le composant en mode tablette soit identique au composant de page de maintenance.

## Captures d'écran

Comportement actuel : 
![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/900d6266-d2fe-4c43-b081-6ad0bac4a29d)

Comportement attendu: 
![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/17314070-06a6-46b8-a578-49f2e4e70478)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

jeremy.lamy.ext@inetum.com

**Comment by deraw** [comment]
Bonjour,

Il n'y a pas de mode tablette pour ces composants, c'est bien le comportement attendu.

**Comment by Jeremy-CNAM** [comment]
Bonjour, il n'y a pas de mode tablette mais le mode mobile doit apparaître à partir de 599 px, pas 959. 
Hors là pour le composant notFound lorsque je l'implémente avec la balise <NotFoundPage>, la vue passe dans la disposition mobile à partir de 959px, et non 599.

Pouvez-vous vérifier s'il n'y a pas éventuellement un problème en faisant appel au composant via la balise <NotFoundPage> et en réduisant la taille de la fenêtre à moins de 960px?

J'ai remarqué ces classes là en inspectant le code (classe de style dont je n'ai pas accès vu que j'implémente simplement le composant) et qui pourraient causer le problème que j'évoque ci-dessus.
![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/e65bfb49-2f07-4d73-8b26-e99f94bda5f9)

**Comment by Becqueva** [comment]
Issue à ré-ouvrir : Cas tablet à gérer 600 - 960px -> passer en mode desktop le sm

**Comment by Becqueva** [comment]
@deraw est-ce que tu t'en charges ou est-ce toi @DavidFyon ?

**Comment by deraw** [comment]
@Becqueva @Jeremy-CNAM 

La modification a bien été prise en compte lors de la refonte des pages d'erreur, il faut mettre à jour Vue Dot (cf. https://github.com/assurance-maladie-digital/design-system/pull/2977)
