### ISSUE TITLE
NotFoundPage : possibilité de mettre un lien externe dans le bouton

### ISSUE THREAD

**Issue by tibolelievre** [assurance-maladie-digital/design-system#2959]
## Description

On a le besoin de pouvoir mettre un lien externe sur le bouton de Retour du template NotFoundPage.
En effet, lors de cohabitation du compte legacy/refonte, l'accueil est sur la partie legacy (et non sur la partie vue)

Je comprendrais un refus de cette évolution étant donné qu'il ne doit pas y avoir beaucoup d'autres cas comme le notre, mais cela n'impactant pas la partie figma, je tente ma chance. 

## Priorisation

- Peu Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

thibaut.lelievre@assurance-maladie.fr

**Comment by deraw** [comment]
Cette fonctionnalité a été intégrée dans le composant `ErrorPage`.
