### ISSUE TITLE
DS Figma : header mode sticky

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#2962]
## Description

1- Le Header en mode sticky en mode desktop et mobile , nexiste pas dans le DS dans figma
2- Pour le dev--digital-design-system, dans le Header en mode sticky en mode mobile, le logo c'est pas bon , petit et pixels
3- Pour le dev--digital-design-system, le logo en mode mobile ,  "Agir ensemble, protéger chacun" ne figurent pas dans ces logos mobile et en plus le logo c pas pareil comme sur figma, le logo est petit

## Comportement attendu

Il faut que le Heade, le header en mode sticky et le logo s'affiche bien  

## Captures d'écran

Pas de header sticky en mode desktop et mobile sur figma
![0BB03FEF-0B85-4F48-A31E-88F11257CD32_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/d51ba950-b487-49cd-aa4c-69e338c6e1fa)

dev--digital-design-system : logo est petit plus faut supprimer la phrase Agir ensemble, protéger chacun
![CA1CD817-4B3D-44B7-98F3-1BD156EF5508_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/dc13c6d4-154c-46df-b750-a6ecd0d11e79)

dev--digital-design-system :  logo est petit et pixélé
![913086AA-A442-48D2-A8F3-3342EDE3BB23_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/5956c032-9997-426d-b6f8-f2772f2eacea)

## Priorisation

- Très prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph tabet - UI Designer - joseph.tabet@inetum.com

**Comment by DavidFyon** [comment]
Fixé par https://github.com/assurance-maladie-digital/design-system/pull/2940 et https://github.com/assurance-maladie-digital/design-system/pull/2965
