### ISSUE TITLE
Configuration du lint

### ISSUE THREAD

**Issue by christopheGaon** [assurance-maladie-digital/design-system#2982]
dod

avoir une conf de lint que tu peux passer sur un nouveau projet et qui assure qualité et lisibilité
pouvoir la moduler selon si on fait une migration d un projet

**Comment by christopheGaon** [comment]
Pas de conf pour le moment

**Comment by deraw** [comment]
- new config files (see https://github.com/antfu/eslint-config/)
- only one package
- https://github.com/eslint-stylistic/eslint-stylistic
- vs code config
- stylelint
- [cspell](https://www.npmjs.com/package/cspell)
- unicorn
- trailing commas ?

**Comment by valentinbecquet** [comment]
Quelle priorité a cette US ?

**Comment by valentinbecquet** [comment]
A voir en juillet ou juin avec l'uploadworkflow
