### ISSUE TITLE
Initialisation de la stack de migration

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#2985]
Créer un projet identique au Stater Kit Vue, mais Nuxt en mode SPA et avec les plugins supplémentaires suivants :
- [x] axios
- [x] Vuex
- [x] Vuex Persist
- [x] Vue i18n
- [x] vue-input-facade
- [x] @mdi/js
- [x] Jest
- [x] Vue Test Utils
- [x] vue-facing-decorator
- [x] nuxt 

https://github.com/assurance-maladie-digital/starter-kit-vue-bridge

**Comment by christopheGaon** [comment]
il reste les 2 PR a merger

**Comment by 4dr1en** [comment]
@4dr1en mettre a jour la dépendance Vuetify
