### ISSUE TITLE
Initialiser le package synapse-bridge

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#2988]
Créer un package `synapse-bridge` pour empaqueter des composant avec Vite (cf. https://github.com/ehsan-shv/vite-vue-lib-template et https://vitejs.dev/guide/build.html#library-mode)

**Comment by christopheGaon** [comment]
ce package est a ajouter aux autres package dans la branche v2-bridge.
A l interieur de ce package il faut cloner le repo suggerer plus haut 
On peut ensuite utiliser la conf de eslint partagée
On peut ajouter un composant et ensuite builder la librairie synapse-bridge contenant ce composant en vue3 et l utiliser dans le starter kit bridge.

**Comment by christopheGaon** [comment]
il me semble qu on avait dit vitest pour la v3. Apres pour le bridge , soit on garde jest soit vitest propose un bridge avec jest . A voir @deraw ?

**Comment by christopheGaon** [comment]
on reste sur jest pour les tests pour aller plus vite
Pour la conf eslint on en met pas au depart

**Comment by DavidFyon** [comment]
sans mauvais jeux de mot, ça va plus vite d'intégrer Vitest avec Vite que Jest

**Comment by christopheGaon** [comment]
fini
