### ISSUE TITLE
Footer : demande ajout prop 'target' à l'objet LinkItem

### ISSUE THREAD

**Issue by Jeremy-CNAM** [assurance-maladie-digital/design-system#3018]
## Description

Actuellement, lorsque l'on clique sur un des liens du footer, nous ne pouvons pas rediriger en ouvrant une nouvelle fenetre car il manque la propriété target à l'objet LinkItem.

## Comportement attendu

Avoir la propriété target

## Priorisation
 
- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Sandrine Chabirand - PPO - [sandrine.chabirand@assurance-maladie.fr](mailto:sandrine.chabirand@assurance-maladie.fr)
Thibaut Lelievre - TechLead - [thibaut.lelievre@assurance-maladie.fr](mailto:thibaut.lelievre@assurance-maladie.fr)
Jérémy Lamy - Developpeur front - [jeremy.lamy.ext@inetum.com](mailto:jeremy.lamy.ext@inetum.com)

**Comment by deraw** [comment]
J'ai ajouté une propriété `openInNewTab` qui applique les bons attributs pour répondre au besoin
