### ISSUE TITLE
FileList : Unknown

### ISSUE THREAD

**Issue by oc8** [assurance-maladie-digital/design-system#3019]
## Description
Je rencontre une erreur quand j'utilise le composant FileList ou UploadWorkflow 

## Reproduction minimale
Utiliser un de ces composants

## Captures d'écran
![Capture d’écran 2023-08-22 à 10 41 49](https://github.com/assurance-maladie-digital/design-system/assets/46847941/36c78867-ff06-4686-8c36-7d945fa6f530)

## Environnement

- OS : Linux
- Navigateur : Arc
- DS : v2.12

## Projet
EI

## Contacts
[odroz.ext@inops.fr](mailto:odroz.ext@inops.fr)

**Comment by deraw** [comment]
Hello @oc8,

Est-ce que tu as bien également mis à jour le package `@cnamts/vue-cli-plugin-vue-dash` ?

**Comment by oc8** [comment]
C'est maintenant fait, mais l'erreur est toujours présente
