### ISSUE TITLE
DS Figma : Rating picker les couleurs ne sont pas identiques entre DS figma et Dev

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#3038]
## Description

Le rating picker, lorsque l'utilisateur laisse son avis, une alert apparaît et il est différent entre le dev et la maquette 
Svp il faut verifier tous les couleurs des icônes, textes et les bordures

## Captures d'écran

Figma:

![EBE077D9-BBC2-4BDA-B466-C7ABE37C3191_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/748ee244-7332-4df3-ad59-d8842489081c)

![4A7B4536-D799-4A43-B8A8-C49FD8434A9A_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/86919c6d-813d-4e6d-afd7-48e7f5067392)

DEV :

![4EAFAD01-3C5A-4FD9-997F-0669E3414B9B](https://github.com/assurance-maladie-digital/design-system/assets/133644194/317bddb9-b811-4a31-b03d-8cbabd9d98be)

![A8194B1C-65D3-4143-BAEF-DD8A5680032A](https://github.com/assurance-maladie-digital/design-system/assets/133644194/f4843517-7020-4a43-a192-0a3604595d78)

![54B5CCCE-A70D-4249-B9C6-9D08C4196F1C](https://github.com/assurance-maladie-digital/design-system/assets/133644194/54ff372d-5eb8-4ca9-b92f-bda8bf964b36)

## Priorisation

- Très prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph Tabet - UI Designer

**Comment by Becqueva** [comment]
US traitée - correction dans Figma pour accélérer la livraison.
