### ISSUE TITLE
DS Figma : Modifier le hauteur de footer a 50px  

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#3039]
## Description

Modifier le hauteur de footer a 50px  a la place de 47px pour que ce soit identique a lenv de Dev

## Captures d'écran

![7020225F-EA54-4FA3-88D0-1964DC31A009_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/57c0a002-5c1e-47e0-a0ee-e7a2aac56db0)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph Tabet - UI Designer

**Comment by Becqueva** [comment]
US traitée et livrée dans la 2.13
