### ISSUE TITLE
HeaderBar: mettre un H1 avec le theme "compte-ameli"

### ISSUE THREAD

**Issue by tibolelievre** [assurance-maladie-digital/design-system#3044]
## Description

Lorsque l'on choisit le theme "compte-ameli", il faudrait qu'il soit entouré d'un H1 (comme c'est le cas lorsque l'on utilise le service-title)

## Comment reproduire

Utiliser le HeaderBar avec le theme compte-ameli

## Reproduction minimale

Utiliser le HeaderBar avec le theme compte-ameli: il n'y a pas de h1 autour de compte ameli

## Comportement attendu

Avoir un h1 autour de compte ameli, lorsque l'on utilise le HeaderBar avec le theme compte-ameli,

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

thibaut.lelievre@assurance-maladie.fr

**Comment by deraw** [comment]
Bonjour,

Cette fonctionnalité demanderait un refactoring trop important, nous n'allons pas l'implémenter.

Cependant, il est possible de le faire de votre côté en utilisant le slot de contenu :
```vue
<template>
	<HeaderBar theme="compte-ameli">
		<h1 class="d-sr-only">
			Compte ameli
		</h1>
	</HeaderBar>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	@Component
	export default class Playground extends Vue {}
</script>
```
