### ISSUE TITLE
RFC sur l'ACL

### ISSUE THREAD

**Issue by christopheGaon** [assurance-maladie-digital/design-system#3057]
### Contexte
cela fait suite a une remontée

vue-browser-acl semble plus forcement maintenu.

### Proposition
1. Est-ce qu'on conserve cette librairie en v2, 
2. Est-ce qu'on la fait evoluer en allant vers celle qu'on pourrait utiliser en vue3.

cf en commentaire les propositions de l'équipe

**Comment by christopheGaon** [comment]
@DavidFyon proposait https://www.npmjs.com/package/vue-simple-acl

il y a aussi ca 

https://npmtrends.com/@casl/vue-vs-acl-vs-browser-acl-vs-casl-vs-express-acl-vs-vue-acl-vs-vue-browser-acl-vs-vue-router-user-roles


@deraw un avis ?

**Comment by deraw** [comment]
Vue Simple ACL n'a pas été mise à jour depuis un an, pour moi la meilleure option est https://github.com/stalniy/casl

**Comment by deraw** [comment]
Je pense qu'il faudrait faire une RFC pour proposer le changement pour la v3 (et aussi pour la v2 en soit mais il ne devrait pas vraiment y avoir de nouveaux projets pour l'instant)
En attendant je vais supprimer le guide puisqu'il n'est plus à jour et on traite ça pour les prochaines versions
