### ISSUE TITLE
Mettre en outlined les pictos des alertes (problème revue)

### ISSUE THREAD

**Issue by Becqueva** [assurance-maladie-digital/design-system#3061]
## Description

Alert -> besoin de revue car problème avec les pictogrammes en filled et non outlined 

## Environnement

- OS : 
- Navigateur : 

## Priorisation

- Peu prioritaire 
- Prioritaire
- Très prioritaire

**Comment by deraw** [comment]
Duplicata de https://github.com/assurance-maladie-digital/design-system/issues/2975
