### ISSUE TITLE
vue-browser-acl

### ISSUE THREAD

**Issue by christopheGaon** [assurance-maladie-digital/design-system#3064]
il y a eu des soucis avec cette lib , on va proposer en rfc la lib 
https://github.com/stalniy/casl/tree/master/packages/casl-vue

ou la lib https://www.npmjs.com/package/vue-simple-acl

cf 
https://github.com/assurance-maladie-digital/design-system/issues/3057

**Comment by deraw** [comment]
Duplicata de #3057
