### ISSUE TITLE
Problème forme et couleur v-alert suite maj 2.14.0

### ISSUE THREAD

**Issue by Jeremy-CNAM** [assurance-maladie-digital/design-system#3070]
## Description

A la suite du passage en 2.14.0, le v-alert ne semblent plus avoir la bonne forme ni la bonne couleur.
![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/1385fe88-cecb-4370-973e-41e34c46ae8b)
![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/52bb06d5-7cbb-421a-8b22-740bbbd4e7eb)

## Comportement attendu

Forme et couleur sur le DS Figma actuel : 
![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/f772dc1c-74f7-4316-82b8-1538dab23fef)
![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/1bbfd221-f5c8-432e-86ae-e97734409c44)

## Priorisation

- Très prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Sandrine Chabirand - PPO - [sandrine.chabirand@assurance-maladie.fr](mailto:sandrine.chabirand@assurance-maladie.fr)
Thibaut Lelievre - TechLead - [thibaut.lelievre@assurance-maladie.fr](mailto:thibaut.lelievre@assurance-maladie.fr)
Jérémy Lamy - Développeur front - [jeremy.lamy.ext@inetum.com](mailto:jeremy.lamy.ext@inetum.com)

**Comment by deraw** [comment]
Bonjour,

En effet il faut maintenant utiliser le composant `AlertWrapper` plutôt que le `VAlert` directement.

Dylan

**Comment by deraw** [comment]
Bonjour,

En effet il faut maintenant utiliser le composant `AlertWrapper` plutôt que le `VAlert` directement.

Dylan

**Comment by christopheGaon** [comment]
Le composant AlertWrapper dont la doc est [ici](https://digital-design-system.netlify.app/composants/feedback/alert-wrapper/#section) repond aux differents problèmes remonté par les équipes : 

- couleur et icones en accord avec la charte de la DICOM
- accessibilité avec le contratse
- gestion de bouton optionnel dans l alert 

Vous pouvez aussi utiliser le VAlert de vuetify dans certains cas d'usage (à voir avec les ux)
