### ISSUE TITLE
Message de confirmation vote rating picker différent de la maquette figma mode mobile.

### ISSUE THREAD

**Issue by Jeremy-CNAM** [assurance-maladie-digital/design-system#3082]
## Description

Le message de confirmation d'un vote de satisfaction en mode mobile n'a pas le même style que sur la maquette figma.

## Comportement attendu

Que le message soit comme sur la maquette (centré et logo à gauche du message)

## Captures d'écran

Rendu actuel : 

![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/e057018f-5a21-4db7-9df4-663b818a43c9)

Rendu attendu : 

![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/32334c9a-dbfa-4f3b-b791-15d565256aef)

## Priorisation
- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Jérémy LAMY
Joseph TABET

**Comment by Becqueva** [comment]
![Uploading Capture d’écran 2023-09-26 à 14.42.53.png…]()

**Comment by Becqueva** [comment]
<img width="1437" alt="Capture d’écran 2023-09-26 à 14 42 53" src="https://github.com/assurance-maladie-digital/design-system/assets/86305670/35f2a9a3-4716-44de-b1e1-8f51dc9f54d0">
