### ISSUE TITLE
Partie gauche du header (Icone l'Assurance maladie + theme 'Compte Ameli') en mode mobile trop tôt

### ISSUE THREAD

**Issue by Jeremy-CNAM** [assurance-maladie-digital/design-system#3084]
## Description

Dans le header, le logo "l'Assurance maladie" et le thème qui l'accompagne (dans mon cas Compte ameli) prennent le style mobile (taille réduite et suppression de la phrase 'Agir ensemble, protéger chacun') à partir de 959 px hors dans les maquettes figma, ce n'est qu'à partir de 599px (taille xs) que ce changement opère.

## Comportement attendu

Que les changements (taille logo + disparition phrase  'Agir ensemble, protéger chacun') ne se fassent qu'à partir de 599px (taille xs) comme dans les maquettes figma. 

## Captures d'écran

comportement actuel à partir de 959 px : 

![image](https://github.com/assurance-maladie-digital/design-system/assets/132574184/d8c2a2f6-1ce2-42d7-b201-fb92f945f1d1)

--> que ce comportement ne s'opère qu'à partir de 599 px.

## Priorisation
- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Jérémy LAMY
Joesph TABET

**Comment by Becqueva** [comment]
Il n'y a pas de paramètrage de taille sur le Figma du DS (il y a 2 versions : desktop et mobile sans blocage de taille) c'est au produit d'adapter la largeur voulue.
