### ISSUE TITLE
CustomIcon

### ISSUE THREAD

**Issue by DavidFyon** [assurance-maladie-digital/design-system#3102]
Ajout du composant à la version bridge.

**Comment by 4dr1en** [comment]
Ce composant a besoin de récupérer l'object d'option de configuration du plugin pour récupérer les icons svg qui peuvent y être passé sous form de string. Actuellement le bridge n'est pas configuré sous forme de plugin.

**Comment by DavidFyon** [comment]
j'ai simplifié le composant
