### ISSUE TITLE
DownloadBtn

### ISSUE THREAD

**Issue by DavidFyon** [assurance-maladie-digital/design-system#3104]
Ajout du composant à la version bridge.

**Comment by deraw** [comment]
> Ce composant a besoin de vueX pour fonctionner, synapse-bidge n'est pas configurer en tant que plugin, est ce que c'est àfaire ? Faut il passer à vueX 4 ?

Je n'ai pas compris la partie sur le plugin, mais oui il faut monter Vuex de version
