### ISSUE TITLE
[Vuejs] : Problème d'enregistrement des composants du Design System CNAM

### ISSUE THREAD

**Issue by Anthony-aram** [assurance-maladie-digital/design-system#3105]
## Description

Bonjour,

J'ai un soucis sur un projet vuejs crée il y a peu de temps.

J'ai une erreur lors de l'exécution des tests unitaires : 
  console.error
    [Vue warn]: Unknown custom element: VIcon - did you register the component correctly? For recursive components, make sure to provide the "name" option.
    
    found in
    
    ---> <PsychologistTable>
           <Root>

J'exemple concerne un VIcon, mais le problème est présent pour tous les composants du Design System. 
Je dois impérativement importer et déclarer les composants du Design System dans mes composants sinon j'ai cette erreur qui apparaît. Sur d'anciens projets, il n'y avait pas besoin de les importer.

## Comment reproduire

1. Installer un nouveau projet vuejs avec le CLI
2. Créer un composant vuejs et utiliser un composant du Design System dans celui-ci, sans l'importer ni le déclarer dans `@Component`.

## Comportement attendu

Il n'est normalement pas nécessaire d'importer manuellement les composants du Design System.

![image](https://github.com/assurance-maladie-digital/design-system/assets/45363078/66671098-3bf9-40e1-bfdf-24e7a49034b6)

## Priorisation

- Prioritaire

## Projet

msp-annuaire-ihm ([git interne]/P1/msp-admin-annuaire-ihm)

## Contacts

Anthony Aram

**Comment by deraw** [comment]
Je ne reproduis pas le bug sur la dernière version du Starter Kit.
De plus, l'erreur de la capture d'écran semble plutôt concerner un composant Vuetify.

Je vais vérifier la configuration de votre projet

**Comment by Anthony-aram** [comment]
Bonjour,

J'ai le même soucis avec par exemple le PaginatedTable du Design System et le HeaderMenu de la librairie access-master-vue

**Comment by deraw** [comment]
> Bonjour,
> 
> J'ai le même soucis avec par exemple le PaginatedTable du Design System et le HeaderMenu de la librairie access-master-vue

Je n'arrive pas à reproduire complètement le problème sur la dev du projet.
Il y a en effet une erreur lors de l'utilisation du composant `HeaderMenu`, mais cela est attendu car il faut importer manuellement les composants de la librairie `access-master-vue`.
