### ISSUE TITLE
Mettre les logos du compte ameli à jour dans le Design System

### ISSUE THREAD

**Issue by AlexisDENY** [assurance-maladie-digital/design-system#3124]
## Description

Les logos validés par la DICOM n'ont pas été importés correctement dans le Design System

## Comment reproduire

Les logos que l'on a à disposition pour le compte ameli ne sont pas ceux qui ont été validés par la DICOM. Merci de les changer pour ceux qui vous ont été fournis dans l'issue [#2526](https://github.com/assurance-maladie-digital/design-system/issues/2526)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Alexis DENY - alexis.deny@assurance-maladie.fr

**Comment by deraw** [comment]
Bonjour,

Est-ce que vous pouvez nous confirmer que les logos étaient les bons avant la PR https://github.com/assurance-maladie-digital/design-system/pull/3036 svp ?

Merci

**Comment by AlexisDENY** [comment]
Bonjour,
Je ne peux pas le confirmer, j'ai fait confiance aux états des tickets sans vérifier les logos.
Après vérifications, le premier logo de l'issue 2526 possède une marge étrange à gauche, alors que cela devrait être celui-ci :
![Logo compte ameli classique](https://github.com/assurance-maladie-digital/design-system/assets/111863355/c139a009-ba02-4092-b5d4-f6e5aee492d8)

**Comment by deraw** [comment]
> Bonjour,
> Je ne peux pas le confirmer, j'ai fait confiance aux états des tickets sans vérifier les logos.
> Après vérifications, le premier logo de l'issue 2526 possède une marge étrange à gauche, alors que cela devrait être celui-ci :
> ![Logo compte ameli classique](https://github.com/assurance-maladie-digital/design-system/assets/111863355/c139a009-ba02-4092-b5d4-f6e5aee492d8)
> 
> 

Est-ce qu'il serait possible de lister à nouveau les logos en s'assurant que les marges soient bonnes svp ?

**Comment by AlexisDENY** [comment]
Je reliste ici les logos avec les bonnes marges.

- Logo classique
![Logo compte ameli classique](https://github.com/assurance-maladie-digital/design-system/assets/111863355/5d987885-bd84-48dd-bd62-910fe49df80d)

- Logo classique "header réduit"
![Logo compte ameli réduit classique](https://github.com/assurance-maladie-digital/design-system/assets/111863355/5a799f51-8bf5-4188-afb0-79f25f9fdb62)

- Logo mobile
![Logo compte ameli mobile](https://github.com/assurance-maladie-digital/design-system/assets/111863355/9eb37ec6-9b0f-4954-acfc-101f8e56a365)

- Logo mobile réduit
![Logo compte ameli réduit mobile](https://github.com/assurance-maladie-digital/design-system/assets/111863355/6e7188e5-a763-4b13-a7d9-bcc0d9766e01)
