### ISSUE TITLE
DatePicker

### ISSUE THREAD

**Issue by DavidFyon** [assurance-maladie-digital/design-system#3172]
Ajout du composant à la version bridge.

**Comment by VachetVirginie** [comment]
@DavidFyon @deraw @christopheGaon @4dr1en Bonjour à tous, pour resoudre les problèmes liès aux differences entre les versions 2 et 3 de vuetify cette lib pourrait etre une solution: https://vue3datepicker.com/

Fonctionnalités manquantes dans la v3:   
- Range
- Birthday
- Start-date
- Show-weekends 

Fonctionnalites manquantes dans la lib:
- Show-weekends

**Comment by 4dr1en** [comment]
todo

- [ ]  accepter une valeur en entré passé a travers la props `model-value` ( = v-model)
- [ ]  emmetre en événement `model:updateValue` lorsque la valeur est modifié au click
- [ ]  feature, mettre en place la props `clearable` et n'afficher la croix que quand celle ci est a `true`
- [ ]  style, corriger le décroché de la bordure en mode `outlined`
- [ ]  comportement, ne pas doubler les slashs quand l'utilisateur les tapes
- [ ]  comportement,  autoriser de selectionner et remplacer plusieurs caractères simultanément dans le champ de text
- [ ]  feature, reporter le filtre de validation `isValidDate`
- [ ]  feature, mettre en place la props `warning-rules`
- [ ]  feature, mettre en place la props `hint`
- [ ]  feature, mettre en place la props `date-format`
- [ ]  feature, mettre en place la props `date-format-return`
