### ISSUE TITLE
Commencer à documenter la migration vers la stack de migration 

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#3277]
merger la pr qui ajoute de la documentation sur l utilisation du router custom de nuxt avec les routes des projets existant en vue2 avec vue-router

review de la pr de @4dr1en sur l utilisation du plugin eslint-vuetify en commande

avoir une page de migration qui explique 
- documenter la migration de vue2 a vue 3
- documenter la migration de vuetify 2 a vuetify 3
- documenter l utilisation de la commande  du plugin eslint-vuetify
- selectionner le projet ayant le moins possible de composants du ds
- documenter la migration vers l option api des vue-class component

**Comment by valentinbecquet** [comment]
Done
