### ISSUE TITLE
Packaging de la librairie du design system nommée v2-bridge

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#3280]
- fichiers `tsconfig.json` https://github.com/logue/vite-vuetify-ts-starter/tree/master
- renommer `synapse-bridge`
- gérer les exports des fonctions et autres pour utilisation dans un projet
- `"packageManager": "pnpm@8.8.0",`
- renommer `main` en `index` ?
- deployer la lib sur npm 
- l importer en local dans un starterkit

**Comment by valentinbecquet** [comment]
Done
