### ISSUE TITLE
Les options de configuration de la taille du text des bouttons sont incohérents

### ISSUE THREAD

**Issue by 4dr1en** [assurance-maladie-digital/design-system#3285]
## Description

Les options de configuration de la taille du text des bouttons sont incohérents, un boutton avec un text défini sur large sera plus petit que la version par défaut.

![btn size](https://github.com/assurance-maladie-digital/design-system/assets/65124433/841a10bc-4e8c-43a1-b20d-36516d05c093)

lien du fichier de configuration:

https://github.com/assurance-maladie-digital/design-system/blob/v2/packages/vue-dot/src/styles/variables.scss

## Comment reproduire

utiliser un composant `v-btn` avec la props `large`.

<details>

```vuejs

<template>
	<PageContainer>
		<v-row
			align="center"
			justify="space-around"
		>
			<v-btn
				x-small
			>Extra small button</v-btn>
			<v-btn
				small
			>Small button</v-btn>
			<v-btn
				medium
			>Regular button</v-btn>
			<v-btn
				large
			>Large button</v-btn>
			<v-btn
				x-large
			>X-large button</v-btn>
		</v-row>
	</PageContainer>
</template>
```

</details>

## Projet

vue-dot

**Comment by deraw** [comment]
Quelle est la PR associée à cette issue ?

**Comment by 4dr1en** [comment]
Il s'agit de décider de la taille de la font des boutton définis comme larges
```
$btn-font-sizes: (
	'x-small': 0.625rem,
	'small': 0.75rem,
	'default': 1rem,
	'large': 0.875rem,
	'x-large': 1.125rem
);
```

**Comment by 4dr1en** [comment]
Je propose de partir sur 
```$btn-font-sizes: (
	'x-small': 0.625rem,
	'small': 0.75rem,
	'default': 1rem,
	'large': 1.125rem,
	'x-large': 1.25rem
);```

Ce qui nous donnerais ça :

![image](https://github.com/assurance-maladie-digital/design-system/assets/65124433/f4407807-aae1-48f9-b748-52ae9c2053dd)

**Comment by valentinbecquet** [comment]
La logique vuetify est la suivante https://v2.vuetifyjs.com/en/api/v-btn/#sass
Je propose de soit : revenir à cette logique, soit mettre default et large à 1rem.

![Image](https://github.com/assurance-maladie-digital/design-system/assets/152852697/e12d1753-35bb-417b-bd24-6d86676153e4)
