### ISSUE TITLE
Rating Picker complexe - changement de la cinematique

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#3298]
## Description

Rating Picker complexe dans le cas ou l'assuré donne une appréciation négative on affiche immédiatement après les choix des questionnaires et le champs libre ci il y en a un (messagerie) et on affiche tout a la fin le message de success, "merci pour votre réponse".

## Comportement attendu

https://www.figma.com/file/yGykrOWySGuBgBSAqHG81c/UI-ameli-Web-Refonte?type=design&node-id=11003%3A36391&mode=design&t=C2Jik7EmgEGCXku8-1

## Captures d'écran

![0DD53795-7E2A-4B20-98E8-6F7BF067B0D7](https://github.com/assurance-maladie-digital/design-system/assets/133644194/8c9d3148-2b2b-4bb5-8c6b-cafbba6d6ba9)
![3F806343-9213-4B18-8018-B19634BAC5E0](https://github.com/assurance-maladie-digital/design-system/assets/133644194/34b7278d-de46-4cd6-b9f5-761b3bc134ca)

![3C035EC7-F14B-4E82-BC5A-CA7726B96D02](https://github.com/assurance-maladie-digital/design-system/assets/133644194/2e08012b-9874-4b23-beea-b9c29fb8eaf4)
![2FDCA6F5-EFF2-40B3-B966-7A8354DCBB4C](https://github.com/assurance-maladie-digital/design-system/assets/133644194/d6246e56-6d41-4a27-ae40-3d7617b38fe7)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

UI-Designer / joseph.tabet@inetum.com
UX-Designer / eric.lebihan@assurance-maladie.fr

**Comment by valentinbecquet** [comment]
Pour répondre aux enjeux du DS, nous proposons 2 solutions : (1) rendre optionnel l'affichage de l'alert en position initiale (ce qui par déduction laisse libre à chaque produit son affichage au moment opportun), cela permet d'afficher une alerte en fin de parcours et non plus directement "dans le parcours", ou (2) afficher en fin de questionnaire.
En attente de validation P1 des solutions pour intégration de la solution
