### ISSUE TITLE
Typographie Source Sans Pro : Dans le Scale category H4 - il manque le font weight Medium sur Figma

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#3299]
## Description

Le font weight de H4 est incorrecte dans la page Fondamentaux "Typographie secondaire" dans le DS (et donc dans celui utilisé pour les titres dans les maquettes)

## Comportement attendu

https://www.figma.com/file/Mf7rEtMTCbw9p3hz8ncMAD/DS-CNAM---2.14.2.1-(Community)?type=design&node-id=104%3A13&mode=design&t=utHyOwu0d5ejmB5e-1

## Captures d'écran

![BEC776A2-FC94-45E0-A3D3-80607E5DE940_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/aeba9305-33da-4a14-b765-15c211c49233)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

UI-Designer / joseph.tabet@inetum.com

**Comment by valentinbecquet** [comment]
Aucune modification n'est réalisée sur le code sauf pour le style button large (il passe de 0.875 à 1 rem).
Les styles de boutons ont été mis à jour et les routes contrôlées sur les composants boutons et boutons divers.
La légende des styles a été revue et corrigée.
