### ISSUE TITLE
Champs de formulaire : Vérifier et tester les champs de formulaire dans tous les status

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#3300]
## Description

Vérifier et tester tous les champs de formulaire qui sont dans le DS dans figma dans tous les status, prends en considération les pictos dans tous les champs.

## Comportement attendu

Version totalement paramétrable sans issue

## Captures d'écran

![9DB6E57D-D5B4-40C7-9367-8BBBA18AF850_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/4d799c2a-6331-43a0-96a9-b21c610b5c01)
![2BF894D5-226F-4B2A-BE7F-533A0063CADE_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/10f9c5f0-fca5-41b5-9c7d-c90cbe03ab84)

le picto ne s'affiche pas :
![FC3AA3B8-AE5F-4EC5-A206-8321879EA680_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/6374f1c8-ec48-4374-9dba-c13a21cc928a)
![40C59349-90EE-42F7-96CD-4E5EA9903803_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/c7dd0565-2424-49a5-902b-acad26d0afcd)
![8E35D676-43BC-43FF-9061-F0C3CB475D14_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/18a35fe4-ecba-46f6-84b5-c4de806db032)

## Priorisation

- Très prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

UI-Designer / joseph.tabet@inetum.com

**Comment by valentinbecquet** [comment]
Issue divisée => #3318 (chemin couleur style) et #3319 (nirfield)
