### ISSUE TITLE
Mettre en place les design tokens Synapse

### ISSUE THREAD

**Issue by DavidFyon** [assurance-maladie-digital/design-system#3303]
https://www.figma.com/file/Y1qJ3Z9V6CWiJ65CFZbdm5/%5BCNAM%5D-UI-Kit-V3.0?type=design&node-id=266%3A626&mode=design&t=C0wNdDuG6olZ0GAK-1

A voir si on intègre ces nouveaux tokens directement dans le projet

TODO :

- [x] Mettre en conformité les fonts et enlever la Mic32
https://www.figma.com/file/Y1qJ3Z9V6CWiJ65CFZbdm5/%5BCNAM%5D-UI-Kit-V3.0?type=design&node-id=315-279&mode=design

- [x] Mettre en conformité des grilles pour le responsive
A voir mode tablette pour les composants
https://www.figma.com/file/Y1qJ3Z9V6CWiJ65CFZbdm5/%5BCNAM%5D-UI-Kit-V3.0?type=design&node-id=316-1185&mode=design

- [x] Mettre en conformité les espaces
https://www.figma.com/file/Y1qJ3Z9V6CWiJ65CFZbdm5/%5BCNAM%5D-UI-Kit-V3.0?type=design&node-id=316-1185&mode=design

- [x] Mettre en conformité les elevations
https://www.figma.com/file/Y1qJ3Z9V6CWiJ65CFZbdm5/%5BCNAM%5D-UI-Kit-V3.0?type=design&node-id=316-1185&mode=design

**Comment by valentinbecquet** [comment]
Epic : tokens
Deadline : début octobre
