### ISSUE TITLE
Initialisation documentation des composants

### ISSUE THREAD

**Issue by DavidFyon** [assurance-maladie-digital/design-system#3333]

**Comment by valentinbecquet** [comment]
Epic : Documentation
Deadline tâche : choix de la technologie pour la documentation : 1 septembre 24
Cahier des charges : 
- voir les composants dynamiquement
- avoir la possibilité d'ajouter du texte (+ code) sur l'accessibilité et l'éco-conception
- templates onglet / section (ex : accessibilité, éco-conception, bonnes pratiques, usage, etc.)

**Comment by valentinbecquet** [comment]
Le choix retenu pour la doc est : Storybook
