### ISSUE TITLE
UploadWorkflow : « Mode sélection libre » ne fonctionne pas

### ISSUE THREAD

**Issue by tibolelievre** [assurance-maladie-digital/design-system#3353]
## Description

Le cas « Mode de sélection libre » présent dans la doc (https://digital-design-system.netlify.app/composants/formulaires/upload-workflow#mode-selection-libre) ne semble pas fonctionner.

## Comment reproduire

J'utilise l'UploadWorkflow dans le cas « Mode sélection libre » et j'upload un deuxième fichier.

J'ai alors l'erreur : 

`Error in v-on handler: "TypeError: setting getter-only property "name""`

## Reproduction minimale

```vue
<template>

	<PageContainer>
		<UploadWorkflow v-model="files" />
	</PageContainer>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	@Component
	export default class Playground extends Vue {
		files: File[] = [];
	}
</script>
``` 

## Comportement attendu

L'upload du deuxième fichier est permis et il est ajouté à la liste des fichiers

## Captures d'écran

![image](https://github.com/assurance-maladie-digital/design-system/assets/118187347/5e005478-35bb-4f06-946a-ef982612c9bd)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

[thibaut.lelievre@assurance-maladie.fr](mailto:thibaut.lelievre@assurance-maladie.fr)

**Comment by deraw** [comment]
> @deraw 
> Merci pour la correction qui semble ok, je peux sélectionner plusieurs fichiers en sélection libre
> Cependant je n'arrive pas à utiliser la visualisation des fichiers **en sélection libre** en ajoutant show-view-btn. Cela fonctionne bien en **sélection non libre**
> 
> Pourrais-tu m'indiquer comment faire ?
> Merci

Hello,

On a un fix qui va être publié pour corriger le problème, tu peux juste laisser la prop sur le composant et ça fonctionnera dans la prochaine version

**Comment by tibolelievre** [comment]
Bonjour, ok j,attends la future version dans ce cas pour re-tester.

**Comment by tibolelievre** [comment]
Bonjour,

J'ai testé la sélection libre avec la version 2.16 et je n'arrive pas à utiliser la visualisation des fichiers en ajoutant show-view-btn. 

Cela fonctionne bien en sélection non libre

Merci de m'indiquer comment je peux faire cela ?
