### ISSUE TITLE
Figma : Modifier la marge entre la bordure et le picto 

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#3361]
## Description

Au niveau de l'affichage du composant ALERT.
Dans le DS Figma, il y a 16 px de marge de padding entre le bord gauche du composant et le picto (4px de bordure + 12) alors que côté dev, il y a 20 px de padding (la bordure à 4 px + 16px de marge).

Il faudrait donc modifier la marge du composant sur Figma pour que ça soit correct.

## Captures d'écran

Dev : 
![DF47DF63-8A6F-4B51-AA91-33AB60BF6DD0_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/115d981b-11b7-4c20-8bad-3c3b279e097a)

Figma :
![AD1CCFFE-A1A9-4247-9A5E-0F246FC5ADDD](https://github.com/assurance-maladie-digital/design-system/assets/133644194/f82f216e-b1ce-4494-94f6-d38466286451)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

joseph Tabet - UI designer

**Comment by valentinbecquet** [comment]
Done
