### ISSUE TITLE
Prop showViewBtn sur Filelist

### ISSUE THREAD

**Issue by valentinbecquet** [assurance-maladie-digital/design-system#3367]
Checker la prop : showViewBtn sur Filelist -> "ça fonctionne sur uploadworkflow" mais sans la visu (juste la dialogbox)

**Comment by DavidFyon** [comment]
A préciser, sur UploadWorkflow la prop est `show-file-preview` et ça fonctionne correctement :

![Image](https://github.com/assurance-maladie-digital/design-system/assets/1822420/05a6c525-7f06-4458-a7ad-bf20bbf50841)
![Image](https://github.com/assurance-maladie-digital/design-system/assets/1822420/3307706c-963c-4e4d-8cb8-60c77d595727)

**Comment by deraw** [comment]
@DavidFyon il y a bien deux props différentes mais l'une est cachée dans les options, je vais regarder, corriger et nettoyer ça

**Comment by deraw** [comment]
@valentinbecquet @DavidFyon pour plus de précision :

Il y a actuellement la prop `show-file-preview` qui permet de prévisualiser un fichier avant de valider la sélection, et une option `show
ViewBtn`, utilisée via la prop `vuetify-options` qui permet d'afficher un bouton dans la liste pour visualiser le fichier sélectionné, mais avec le comportement à implémenter côté projet.

Maintenant on va avoir deux props à proprement parler : `show-file-preview` et `show-view-btn`, sans besoin d'implémentation côté projet (on fait déjà la prévisualisation à un endroit, on peut le faire à deux)

Vu que c'est un ajout de prop, on garde la rétrocompatibilité avec l'ancien fonctionnement pour ne pas avoir deux boîtes de dialogues pour ceux qui utilisent le composant avec une implémentation personnalisée.
