### ISSUE TITLE
Ajouter linter a11y + voir ce qui manque par rapport RGAA

### ISSUE THREAD

**Issue by DavidFyon** [assurance-maladie-digital/design-system#3385]

**Comment by valentinbecquet** [comment]
Un mail est parti à l'équipe RGAA
" Dans le cadre de la fabrication d’un design system nous utilisons le pluggin A11Y (https://www.a11yproject.com/checklist/) pour automatiser le contrôle de l’accessibilité sur nos composants. (https://www.npmjs.com/package/eslint-plugin-jsx-a11y) 
Dans le cas où vous avez connaissance de ce pluggin (et de cette liste de checklist), nous souhaiterions savoir si ces règles suffisent à respecter le RGAA ou si différence il y a, seriez-vous en mesure de nous les indiquer ?

Par ailleurs, avez-vous un pluggin à nous conseiller pour automatiser les contrôles ? 
Nous travaillons avec vuejs sur une base vuetify."

**Comment by valentinbecquet** [comment]
Réponse du RGAA : 
" Aucun outil de tests automatiques ne permet de s'assurer de la 
conformité au RGAA. On estime qu'au mieux ils couvrent 20% des tests. Il 
est par ailleurs écrit sur la page de votre outil (que nous ne 
connaissons pas, nous ne pouvons donc pas nous prononcer sur sa qualité) 
:

"Does this checklist guarantee my site is accessible?
No. However, addressing the issues called out in this checklist will 
help improve the experience for everyone who uses your site.""

**Comment by valentinbecquet** [comment]
Ajouter en plus une doc sur tanaguru (avec page d'exemple sur les composants) sur la doc
