### ISSUE TITLE
DS Figma : Problème des couleurs dans les radios boutons

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#3396]
## Description

Dans Figma les radios buttons pas de distinction de couleurs entre champ sélectionnable et champ sélectionné 

## Comportement attendu

Ajouter une option gris foncé pour les radios buttons sélectionnable

## Captures d'écran

En mode DEV :
![06C7664C-FA72-4766-A3D4-47A60175ACA0](https://github.com/assurance-maladie-digital/design-system/assets/133644194/49026390-df75-4bb7-82bd-451de2a8e97e)

Figma :
![A2D27820-1A01-4740-BB13-480114F47758](https://github.com/assurance-maladie-digital/design-system/assets/133644194/64e8bab1-08b8-49eb-aed9-df4ac05ec694)

Option en Figma :
![61F3E88C-49E5-4FBA-AD4D-17B195E43097_4_5005_c](https://github.com/assurance-maladie-digital/design-system/assets/133644194/00298b41-5341-4c0a-b649-d79ca3634176)

## Priorisation

- Très prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph Tabet - UI Designer

**Comment by valentinbecquet** [comment]
Modification sur FIGMA uniquement (puisque c'est un composant vuetify) du style de couleur à Text high emphasis (noir 87%) pour l'état default
Modification du composant checkbox pour cohérence graphique
Application du style disabled au composant checkbox à l'état disabled (correction bug)
