### ISSUE TITLE
Format de date de retour du DatePicker dans le composant FiltersSideBar

### ISSUE THREAD

**Issue by ArthurBrgn** [assurance-maladie-digital/design-system#3397]
Le bug était sensé être corrigé suite à cette issue : 

[https://github.com/assurance-maladie-digital/design-system/issues/3233](https://github.com/assurance-maladie-digital/design-system/issues/3233)

J'ai bien le package du DS mis à jour (2.15) et le problème persiste toujours.
Lorsque j'utilise un composant DatePicker dans le FiltersSideBar, même en renseignant l'attribut date-format-return="YYYY-MM-DD", la date récupérée est sous le format DD/MM/YYYY :

![image](https://github.com/assurance-maladie-digital/design-system/assets/19926336/cc14eaf5-c5fc-4c21-9884-5fd66247c725)

A noter que tout fonctionne bien en dehors du composant FiltersSideBar

**Comment by DavidFyon** [comment]
Hello Arthur :

Voici un playground qui fonctionne avec la version 2.15.
J'ai mis en-dessous un screenshot des dates récupérées au bon format.

`<template>
	<div>
		<FiltersSideBar
			v-model="filters"
			@update:value="updateFilters"
		>
			<template #birthdate="{ on, attrs }">
				<DatePicker
					v-bind="attrs"
					birthdate
					outlined
					date-format="DD/MM/YYYY"
					hint="Format JJ/MM/AAAA"
					date-format-return="YYYY MM DD"
					v-on="on"
				/>
			</template>

			<template #studiesdate="{ on, attrs }">
				<DatePicker
					v-bind="attrs"
					outlined
					date-format="DD/MM/YYYY"
					hint="Format JJ/MM/AAAA"
					date-format-return="YYYY MM DD"
					v-on="on"
				/>
			</template>
		</FiltersSideBar>

		<DatePicker
			outlined
			date-format="DD/MM/YYYY"
			hint="Format JJ/MM/AAAA"
			date-format-return="YYYY MM DD"
			@change="getValue($event)"
		/>
		{{ value }}
	</div>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';
	@Component
	export default class Playground extends Vue {
		value = '';
		filters = [
			{
				name: 'birthdate',
				title: 'Date de naissance'
			},
			{
				name: 'studiesdate',
				title: 'Date d\'ODD'
			}
		];
		updateFilters(): void {
			console.log(this.filters);
		}
		getValue(value: string): void {
			this.value = value;
		}
	}
</script>
`

![Capture d’écran 2024-02-19 à 12 10 11](https://github.com/assurance-maladie-digital/design-system/assets/1822420/eb412c97-a04c-4cb8-861c-1c585d478b63)

**Comment by deraw** [comment]
Sans reproduction du bug, je ferme l'issue
