### ISSUE TITLE
Datepicker ne renvoie la valeur de l'input que si c'est une date

### ISSUE THREAD

**Issue by mbelluzzi** [assurance-maladie-digital/design-system#3450]
## Description

Lorsque j'utilise le `@change` sur le composant DatePicker et que je rentre une date au format invalide, la valeur bind par `v-model` n'est pas mis à jour.

## Comment reproduire

1. Utiliser le composant DatePicker
2. bind un state via `v-model`
3. écouter l'évènement @change du DatePicker
4. Rentrer une date au format invalide
5. Constanter que l'évènement `@change` n'est pas émis
6. Constater que la valeur bind par `v-model` n'a pas été modifiée

## Comportement attendu

On devrait avoir la valeur rentrée dans le champ même si elle est à un format invalide

## Captures d'écran

![image](https://github.com/assurance-maladie-digital/design-system/assets/81155793/898752cf-b6f0-40b0-8fbe-c72626be3285)
![image](https://github.com/assurance-maladie-digital/design-system/assets/81155793/c99ba506-0773-45a6-a9c3-3db9bbeaabb8)
![image](https://github.com/assurance-maladie-digital/design-system/assets/81155793/dadac9b9-4e03-4686-a792-b686c64cd7aa)
![image](https://github.com/assurance-maladie-digital/design-system/assets/81155793/0b8113b7-ef1d-487d-8033-90a622e5e94b)
![image](https://github.com/assurance-maladie-digital/design-system/assets/81155793/4b21c470-9e24-48b0-9fc3-164135424d2d)

## Environnement

- OS : Ubuntu
- Navigateur : Firefox

## Priorisation

- Prioritaire

## Projet

SOPHIA

## Contacts

Slack: Michaël Belluzzi
Mail: michael.belluzzi.externe@capgemini.com

**Comment by 4dr1en** [comment]
Ceci est le comportement attendu étant donné que le composant retourne une ate au format ISO8601.

Vous devriez surement utiliser l'évenement 'input' plutot que 'change'.

https://digital-design-system.netlify.app/composants/formulaires/date-picker/#section/api


N'hesitez pas à rouvrir l'issue si cette réponse ne répond pas à votre question.

**Comment by mbelluzzi** [comment]
Bonjour,

je rouvre l'issue car les deux events (input ou change) ne renvoie pas la string tant que celle-ci n'est pas une date au bon format:

![{F2A6E130-B04D-422D-BD7B-88FCAEC28BF0}](https://github.com/user-attachments/assets/86276520-6ef9-47c8-8f23-8c2f7b5efaca)

![{85B5D344-2F87-45AE-A334-1D13B8A51C57}](https://github.com/user-attachments/assets/11dfbef8-8178-4f0a-8768-3e9ac951ef8e)

![{3F808166-FD22-4DC1-B204-D829944C1666}](https://github.com/user-attachments/assets/de176d14-20ff-4e6a-8488-b302fe961fa8)

Le cas d'usage ici est de pouvoir reset la valeur du champ à l'intérieur avec un bouton "réinitialiser les champs", ce qui est impossible puisque la valeur retournée par le composant reste une string vide tant que la valeur n'est pas une date ISO

**Comment by DavidFyon** [comment]
Bonjour,

Le comportement est normal car le champ n'est pas valide :
![Capture d’écran 2024-11-08 à 12 36 58](https://github.com/user-attachments/assets/3581f28f-a8b4-453d-a105-f7e70daa547a)

Toutefois cela peux être résolu de cette façon :
```vue
<template>
	<div class="pa-4">
		<DatePicker
			v-if="show"
			ref="datepicker"
			v-model="selectedDate"
			birthdate
			date-formate="DD/MM/YYYY"
			date-format-return="YYYY-MM-DD"
			outlined
			clearable
			label="Date de naissance"
			@keyup.enter="onEnter"
			@input="onFieldInput"
		/>
		<VBtn @click="reset">
			Reset
		</VBtn>
	</div>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	@Component
	export default class Playground extends Vue {
		selectedDate: string | null = null;
		show = true;

		onEnter(): void {
			console.log('ENTER', this.selectedDate);
		}

		onFieldInput(): void {
			console.log('INPUT', this.selectedDate);
		}

		reset(): void {
			this.show = false;
			this.$nextTick(() => {
				this.show = true;
			});
		}
	}

</script>
```
