### ISSUE TITLE
Fusion option et composition API (Bridge & V3)

### ISSUE THREAD

**Issue by valentinbecquet** [assurance-maladie-digital/design-system#3454]
**Étude prioritaire**
Il est demandé de répondre à la question par un argumentaire démonstratif (démo).
Pour des raisons de maintenabilité et de réduction des erreurs de répercussion, **est-il possible d'avoir une seule librairie design system (contenant les composants et templates) combinant des composants configurés en options API et d'autres en composition API** ?

Exigence
Cette librairie doit être compatible avec les SK Bridge et SK v3

**Comment by DavidFyon** [comment]
--WIP--

**Avantages :**
- 1 seul package à gérer

**Inconvénients :**
- Pas de possibilité de faire évoluer les versions (Vue 3.3.0, Vuetify 3.3.0...) pour que le Bridge puisse toujours fonctionner (Vskeleton, Vuex...) -> le dev de la V3 sera bridée ou alors il faut repasser sur certains composants pour les rendre compatibles
- Les évolutions globales de la v3 (design tokens...) auront un impact sur le Bridge
- Contraindre les projets de passer sur du Pinia par ex alors qu'ils ne veulent peux-être pas ?
- Refaire une doc pour les nouveaux plugins

**Pour le produit, peu d'impact pour upgrade sa librairie peux importe la solution :**
- 1 seul package : passer de synapse1.1 à synapse1.2
- 2 packages : passer de synapse-bridge1.1 à synapse1.2
