### ISSUE TITLE
[Vue bridge] Composant PaginatedTable => Rendre la persistance de la pagination optionnelle

### ISSUE THREAD

**Issue by ArthurBrgn** [assurance-maladie-digital/design-system#3457]
## Description

Dans la version actuelle du DS, il n'est pas possible de désactiver la persistance de la pagination du composant PaginatedTable.
C'est problématique car dans la plupart des cas nous ne souhaitons pas persister l'état de la pagination entre les pages.

## Comportement attendu

A intégrer dans la roadmap Vue bridge : 

Par défaut ne pas persister l'état de la pagination.
Persister uniquement si on le précise via une props.

**Comment by DavidFyon** [comment]
@ArthurBrgn @valentinbecquet   pour moi cela revient à utiliser le v-data-table de Vuetify
