### ISSUE TITLE
Extract données script Adrien

### ISSUE THREAD

**Issue by valentinbecquet** [assurance-maladie-digital/design-system#3460]
A réaliser la semaine du 1er avril 2024
Réaliser une extraction de données pour les utilisateurs (et les occurrences des composants + templates)
**Méthode : Utiliser le script d'Adrien**

**Comment by 4dr1en** [comment]
[report.xlsx](https://github.com/assurance-maladie-digital/design-system/files/14834025/report.xlsx)
