### ISSUE TITLE
Bug SearchFieldList

### ISSUE THREAD

**Issue by DavidFyon** [assurance-maladie-digital/design-system#3496]
![Image](https://github.com/assurance-maladie-digital/design-system/assets/1822420/57c19667-0e57-4062-a05d-b48aecff4120)

**Comment by chaapai** [comment]
Pour info, on a fait ça chez nous pour le filtre :
https://git.digital.cnamts.fr/dpvs/meps/meps-ihm/-/blob/develop/src/components/CustomSearchFilter/CustomSearchFilter.vue

Deux choses intéressantes :
- Les cases affichées cochées et la sélection réalisée par l'utilisateur sont dans deux variables séparées (checkboxes et selectedValues)
- on a utilisé le composant v-virtual-scroll qui permet de n'afficher que N résultats à l'écran et charger les données plus rapidement

Améliorations possibles :
- pouvoir tout cocher/décocher
- afficher éventuellement un récap des cases cochées dans ce style là : choix1, choix2, choix3, +4 autres
- ne pas tenir compte des accents dans la recherche
- des TUs :stuck_out_tongue:
