### ISSUE TITLE
Problème de Height sur SelectBtnField

### ISSUE THREAD

**Issue by bborlet** [assurance-maladie-digital/design-system#3520]
## Description

Lors du mode multiline (inline=false) un height de 48px forcé sur le SelectBtnField, précisiment sur le v-btn-group

## Comment reproduire

Utiliser le composant en mode multiligne

## Reproduction minimale

```js
<SelectBtnField
				:items="[
	{
		text: "Demande de Pension d'Invalidité",
		value: "invalidite",
	},
	{
		text: "Demande de Pension d'Invalidité de Veuf(ve)",
		value: "invalidite-veuf",
	},
	{
		text: "Demande d'ASI",
		value: "asi",
	},
]"
				label="Type de CERFA"
			/>
```
## Comportement attendu

Les boutons devraient etre les uns sous les autres

## Captures d'écran
<img width="1209" alt="Pasted image 20240529150116" src="https://github.com/assurance-maladie-digital/design-system/assets/171041990/3f05a6c8-2690-4832-8e61-24e56b439ee9">

<img width="311" alt="Pasted image 20240529150252" src="https://github.com/assurance-maladie-digital/design-system/assets/171041990/7157f4d5-6d71-4809-b6f9-4329553003a3">

## Environnement

- OS : MacOS
- Navigateur : Chrome

## Priorisation

- Prioritaire

## Projet

Refonte Inva

## Contacts

Benjamin Borlet

**Comment by DavidFyon** [comment]
https://github.com/assurance-maladie-digital/starter-kit-vue/pull/52

**Comment by DavidFyon** [comment]
![Image](https://github.com/assurance-maladie-digital/design-system/assets/1822420/c88cb2ba-6c05-4301-94f9-4f01df4ea5e4)
