### ISSUE TITLE
Impossible de customiser certains props de vuetify-options DatePicker

### ISSUE THREAD

**Issue by bborlet** [assurance-maladie-digital/design-system#3523]
## Description

Impossible de changer la `bgColor` du datePicker 

Cette computed empêche désormais (par rapport a la version non bridge) de passer des props arbitraires tel que bgColor au textfield du date picker.
```js
textFieldOptions() {
			let errorMessages = this.$attrs.errorMessages;
			return {
				value: this.lastTypeAddedDate === 'date' ? this.formatDate(this.date) : this.inputValue,
				type: "text",
				hideDetails: "auto",
				label: this.label,
				"aria-describedby": this.label,
				variant: this.getVariant,
				disabled: this.disabled,
				hint: this.hint,
				prependIcon: !this.outlined ? this.prependIconValue : 'undefined',
				appendInnerIcon: (this.outlined || this.appendIcon) ? this.calendarIcon : undefined,
				persistentHint: true,
				color: "#0C419A",
				rules: this.rules,
				class: ['textFieldClasses', {'warning-style': this.errorMessages.length > 0}],
				errorMessages: errorMessages || [],
			};
		},
```

## Comment reproduire
En utilisant la props vuetify-options tel que dans la doc

```js
<DatePicker
					label="Date de naissance"
					outlined
					:vuetify-options="{ textField: { bgColor: 'white' } }"
				/>
```

## Comportement attendu

Les props passées au champ textField devraient etre propagées.
## Captures d'écran

<img width="390" alt="image" src="https://github.com/assurance-maladie-digital/design-system/assets/171041990/309779c3-9ca4-4507-af60-cb29591e2b1c">

## Projet

Refonte inva

## Contacts

Benjamin Borlet

**Comment by DavidFyon** [comment]
C'est normal car on a été obligé d'utiliser un plugin externe à Vuetify pour répondre aux besoins qui n'étaient plus couverts avec Vuetify3, du coup les vuetify-options ne sont plus accessibles pour ce composant, il doit pouvoir être customisé en css.
