### ISSUE TITLE
Dans Design System Figma H4 non disponible

### ISSUE THREAD

**Issue by adetourn** [assurance-maladie-digital/design-system#3537]
## Description

Je travaille sur la réécriture de Médialog + dans Figma et je ne peux plus sélectionner la police H4 SSP. J'avais créé des titres avec cette police, j'ai voulu changer la police pour voir ce que ça ferait, et je peux plus revenir en arrière.

## Reproduction minimale

(https://www.figma.com/design/B1d2yoABdVINr4yNbFsPqA/R%C3%A9%C3%A9criture-M%2B?node-id=65-3712&t=8aEklwti6NLeIb8a-0)

## Comportement attendu

Je voudrais pouvoir sélectionner la police H4 SSP

## Captures d'écran

![image](https://github.com/assurance-maladie-digital/design-system/assets/173144245/fb934328-97c3-4272-b133-6382891f45e7)

## Environnement

- OS : PC
- Navigateur : Windows 11

## Priorisation

- Peu prioritaire 
- Prioritaire x
- Très prioritaire

## Projet

Médialog +

## Contacts

annick.detourne@capgemini.com

**Comment by valentinbecquet** [comment]
Votre problème est-il toujours d'actualité ? @adetourn

**Comment by adetourn** [comment]
Non, j'ai utilisé une autre police.

**Comment by valentinbecquet** [comment]
@adetourn ah, je pense que votre problème vient du téléchargement de la font
Pour simplifier le développement, je vous invite à conserver la font Source Sans Pro afin d'éviter un écart avec le DS et les potentiels bugs/écarts graphiques que cela engendrerait. 
![Uploading Capture.PNG…]()
