### ISSUE TITLE
HeaderBar Hydration style mismatch avec slot 

### ISSUE THREAD

**Issue by antoinecnam** [assurance-maladie-digital/design-system#3552]
## Description

Dans un projet Nuxt 3, lors de l'utilisation du slot `#navigation-bar-content` dans un composant `HeaderBar` il y a un warning Hydration style mismatch

## Comment reproduire

Dans un composant :
```
    <HeaderBar
		service-sub-title="Portail d’administration"
		service-title="Compte ameli"
		home-arialabel="Accueil - Habilitations des fonctionnalités du compte"
	>	
		<template #navigation-bar-content >
			<div>
				<p>test</p>
			</div>
		</template>
	</HeaderBar>
```

## Captures d'écran

![image](https://github.com/assurance-maladie-digital/design-system/assets/172277015/84b34898-8586-4c90-a519-5b9dfab7dc37)

## Environnement

- Navigateur : Chrome

## Priorisation

- Peu prioritaire 

## Projet

SSA_PORTAIL_AS_ADMINISTRATION / ASPA_X

## Contacts

Antoine Gosset Dev Front

**Comment by 4dr1en** [comment]
La librairie n'est pas encore compatible avec le rendu côté serveur ssr). Pour utiliser les composants sans erreurs, vous devez soit définir la propriété 'ssr' à false dans le fichier 'nuxt.config.ts', soit utiliser le composant en l'enveloppant dans le composant Nuxt 'ClientOnly'. https://nuxt.com/docs/api/components/client-only

@DavidFyon
