### ISSUE TITLE
DatePicker blur non souhaité

### ISSUE THREAD

**Issue by bborlet** [assurance-maladie-digital/design-system#3553]
## Description

Bonjour,

J'ai l'impression qu'un blur est emit au click sur l'icon calendrier ce qui rend le champs invalid avant meme la saisie utilisateur

## Comment reproduire

Mettre un datepicker vue3 avec la regle required
Clicker sur le petit calendrier pour saisir une date

## Captures d'écran
Avant click sur le calendar
<img width="495" alt="image" src="https://github.com/assurance-maladie-digital/design-system/assets/171041990/46c5cbc3-99e0-41b7-857f-61721b1d7eaa">
Apres click sur le calendar :
<img width="409" alt="image" src="https://github.com/assurance-maladie-digital/design-system/assets/171041990/e877fda0-8aed-4743-89db-9b1151f2cb4c">

Pour moi la regle required ne devrait pas rentrer en jeu jusqu'au blur réel la j'ai l'impression que ca fait focus -> blur -> focus lors du click sur le calendrier
## Projet

Refonte Inva

## Contacts

Benjamin Borlet

**Comment by VachetVirginie** [comment]
Fix avec une precedente issue
