### ISSUE TITLE
DS Figma : Logo titre et sous-titre /  La font-family ne sont pas celles attendues.

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#3577]
## Description

La font-family de titre et sous-titre ne sont pas identiques entre Figma et DEV.
Figma : le Titre a un font-family "cabin" , le font weight Semibold , font-size: 16px 
Dev : le Titre a un font-family "Source Sans 3", le font weight Medium , font-size: 1.125rem - 18px

Figma : le sous-titre à un font-family "cabin" , font-size:  12px
Dev : le sous-titre à un font-family "Source Sans 3" , font-size: .875rem - 14px

NB : Besoin d'ajouter dans le design systeme Figma le logo titre et sous-titre en mode sticky

## Comportement attendu

La font-family devrait être "Source Sans 3",  meme font-size et font weight

## Captures d'écran

Figma 
![C3FD8263-D6ED-4975-8F26-41F0A7FA4545](https://github.com/assurance-maladie-digital/design-system/assets/133644194/a7f17c25-efd1-4923-bb84-cd3abdab7d02)

Figma
![A3534029-FED2-43A1-A20C-6D942194329E](https://github.com/assurance-maladie-digital/design-system/assets/133644194/1ba071d0-ce7c-47be-a343-44d84e51e5f2)

DEV 

Titre
![74720701-8085-43DA-A4EC-C0557D0E9D92](https://github.com/assurance-maladie-digital/design-system/assets/133644194/023a6e66-00c4-4da2-b316-a7afe6693c1e)

Sous-titre
![38332022-A6A2-4387-AE33-D8D4BB555109](https://github.com/assurance-maladie-digital/design-system/assets/133644194/d5e4ca6d-2248-47b9-bdc4-a17d426150a0)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph Tabet - UI DESIGNER

**Comment by valentinbecquet** [comment]
Issue résolue sur FIGMA
Modification des font par Source sans 3 (cabin => SS3)
