### ISSUE TITLE
Figma / DEV : Accessibilité non conforme - L'indication de format (JJ/MM/AAAA) disparait visuellement lors de l'affchage du message d'erreur 

### ISSUE THREAD

**Issue by JosephTabet** [assurance-maladie-digital/design-system#3638]
## Description

Besoin d'ajouter le format JJ/MM/AAAA lorsque le message d'erreur est affiché.

Dans le calendrier mettre par ex la date du jour pour que le message d'erreur s'affiche.
Obtenu : l'indication de format JJ/MM/AAAA disparaît visuellement lorsque le message d'erreur est affiché

## Comportement attendu

Ajouter l'accès à la prop 'persistent-hint' via le datePicker

## Captures d'écran

![8952E607-95C3-4371-B151-B4CDBE677F2F](https://github.com/user-attachments/assets/06013c32-ba65-41e8-b781-94e57c6b4da0)

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Joseph Tabet - UI Designer

**Comment by valentinbecquet** [comment]
En cours

**Comment by valentinbecquet** [comment]
A vérifier si c'est un problème de doc uniquement ou si c'est bien un problème composant, je ré-ouvre l'issue.

**Comment by tibolelievre** [comment]
Pour info, ce problème existe chez nous donc pas seulement dans la doc.
