### ISSUE TITLE
DatePicker avec propriété vuetify-options

### ISSUE THREAD

**Issue by eartru-N** [assurance-maladie-digital/design-system#3649]
## Description

Lors de l'utilisation du DatePicker avec l'attribut vuetify-options contenant la propriété rules afin de mettre le champ required, l'attribut ne semble pas être pris en compte.

## Comment reproduire

Dans le template 
``` html
<DatePicker v-model="victime.dateDeNaissance"
		    label="Date de naissance"
		    birthdate
		    outlined
		    :vuetify-options="{
			   ...dateDeNaissanceOptions,
		   }"
/>
```
Dans le script
``` typescript
import {ValidationRule} from '@cnamts/synapse-bridge/src/rules/types'

const rulesComputed = computed((): ValidationRule<string>[] => {
	return [...new Set([required])]
})
const dateDeNaissanceOptions = {
	rules: rulesComputed
}
```
Dans ma page, je met mon curseur sur la date puis je sors du champs en cliquant à côté. Il n'y a pas de message spécifiant que le champ est obligatoire.

## Comportement attendu

Lorsque je sors du champs j'aimerais qu'il y est un message "Le champ est requis." qui apparait en dessous du DatePicker.

## Environnement

- OS : Windows 11 Pro
- Navigateur : Firefox 128

## Projet

Refonte Rentes

## Contacts

Estelle ARTRU, Loris PERCIN

**Comment by DavidFyon** [comment]
Ex d'utilisation :

<date-picker v-model="date" :rules="validRules" label="Date"/>
<date-picker v-model="date" :warning-rules="warningRules" hint="defaultHint" label="Date" outlined/>

------

import {required} from "@cnamts/synapse-bridge/rules/required";
import {notAfterToday} from "@cnamts/synapse-bridge/rules/notAfterToday";
import {notBeforeToday} from "@cnamts/synapse-bridge/rules/notBeforeToday";

data() {
	return {
		date: dayjs().format('DD/MM/YYYY'),
		validRules: [required],
		warningRules: [notAfterToday, notBeforeToday]
