### ISSUE TITLE
Couleurs du Portail Agent

### ISSUE THREAD

**Issue by eartru-N** [assurance-maladie-digital/design-system#3652]
## Description

Dans le fichier bootstrapColors.scss il manque des couleurs que le Portail Agent utilise.

## Comportement attendu

Je souhaite qui y est toutes les couleurs "brand" du portail agent, comme décrit ci-après.
``` css
// Brand COLORS
$brand:                 #4a3f59; // General UI color : darkblue
$brand-secondary:       #ac1c81; // accent color     : fuschia
$brand-muted:           #b7cbd6; // light muted blue
$brand-muted-lite:      #E7F3F9; // ligth bright blue
$hilite-primary:        #0062ac; // intense blue
$hilite-secondary:      #e6bebf; // rosa for hovers
```
Ces informations proviennent du fichier _cnam-theme-cobalt disponible dans le package @pav2/cnamui

## Projet

Refonte Rentes

## Contacts

Estelle ARTRU, Loris PERCIN

**Comment by DavidFyon** [comment]
Bonjour, 

Les couleurs demandées sont disponibles sur la dernière version du package `"@cnamts/design-tokens": "2.16.8"`

```vue
$vd-brand: #4a3f59;
$vd-brand-secondary: #ac1c81;
$vd-brand-muted: #b7cbd6;
$vd-brand-muted-lite: #E7F3F9;
$vd-hilite-primary: #0062ac;
$vd-hilite-secondary: #e6bebf;
```
