### ISSUE TITLE
[Vue 2] Possibilité de customiser le label du champ NirField

### ISSUE THREAD

**Issue by ArthurBrgn** [assurance-maladie-digital/design-system#3686]
Il faudrait donner au développeur la possibilité de changer le label du champ NirField afin d'avoir un autre label que "Numéro de sécurité sociale"

**Comment by valentinbecquet** [comment]
Merci Arthur, on va étudier ta demande d'ici la fin de semaine pour te donner une visibilité sur son traitement assez rapidement.

**Comment by valentinbecquet** [comment]
A priori aucune contre indication pour intégrer ton besoin tant que "Numéro de sécurité sociale" est le label par défaut à l'appel du composant. Un ajout de doc est également à intégrer pour aider à la définition du label (cas mobile, limite d'un label trop long, accessibilité, etc.).
L'issue n'est pas embarquée pour le sprint d'août néanmoins nous ferons cet ajout courant septembre.
