### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by valentinbecquet** [assurance-maladie-digital/design-system#3696]
**Mise à niveau Alerts (renommer _si possible_ AlertWrapper en Alerts)**

**Besoin**
Mettre en conformité le composant Alerts pour Synapse 
Lien vers composant VueDot/Bridge : https://digital-design-system.netlify.app/composants/feedback/alert-wrapper

- Ce composant est à concevoir sous vue3 en accord avec v3.vuetify
- Contrôler les marges, les couleurs et les fonts en accord avec les tokens
- Optimiser le composant (code) pour l'éco-conception et inclure le même niveau de permissivité que celui du Bridge (slots, personnalisation des labels, etc.).

Le découpage du composant et de ses sous-composants peut être différent entre la librairie développée (Synapse) et l'UI kit des designers selon les besoins du logiciel FIGMA. Néanmoins, en cas de différence, une documentation type mode d'emploi sur FIGMA doit être réalisé.

**Critères d'acceptances pour la revue de la conception** 

- [x] Le composant intègre sur FIGMA, en cas d'utilisation de composant vuetify, les propriétés vuetify utiles au design
- [x] Le composant est maquetté sur FIGMA (tous les états + devices mobile, tablet et desktop)
- [x] La documentation sur FIGMA type mode d'emploi est réalisée (optionnelle)
- [ ] La documentation des usages est réalisée et disponible pour les développeurs
Lien du composant sur FIGMA : https://www.figma.com/design/m2tWjSODYdgi5POFx0cmJr/Synapse?m=auto&node-id=317-1396

**Critères d'acceptances pour la revue du développement (destinée à la publication)** 

- [x] Le composant est conforme aux maquettes (tokens)
- [x] Le composant est fonctionnel
- [x] Le composant est responsive (mobile, tablet et desktop)
- [x] Le composant répond aux critères d'accessibilité (test Tanaguru + A11y linter)
- [x] Le composant passe les tests du DS
- [x] La documentation API et exemples est réalisée

**Comment by valentinbecquet** [comment]
Modification effectuée des radius à 4 (prop "rounded") sur Figma

**Comment by 4dr1en** [comment]
https://github.com/assurance-maladie-digital/design-system-v3/pull/58

**Comment by DavidFyon** [comment]
![Image](https://github.com/user-attachments/assets/07c41cc1-fe8b-450b-be32-e591e1663fbb)
