### ISSUE TITLE
NotificationBar

### ISSUE THREAD

**Issue by valentinbecquet** [assurance-maladie-digital/design-system#3697]
**Mise à niveau NotificationBar**

**Besoin**
Mettre en conformité le composant NotificationBar pour Synapse 
Lien vers composant VueDot/Bridge : https://digital-design-system.netlify.app/composants/feedback/notification-bar#section/utilisation

- Ce composant est à concevoir sous vue3 en accord avec v3.vuetify
- Contrôler les marges, les couleurs et les fonts en accord avec les tokens
- Optimiser le composant (code) pour l'éco-conception et inclure le même niveau de permissivité que celui du Bridge (slots, personnalisation des labels, etc.).

Le découpage du composant et de ses sous-composants peut être différent entre la librairie développée (Synapse) et l'UI kit des designers selon les besoins du logiciel FIGMA. Néanmoins, en cas de différence, une documentation type mode d'emploi sur FIGMA doit être réalisé.

**Critères d'acceptances pour la revue de la conception** 

- [x] Le composant intègre sur FIGMA, en cas d'utilisation de composant vuetify, les propriétés vuetify utiles au design
- [x] Le composant est maquetté sur FIGMA (tous les états + devices mobile, tablet et desktop)
- [ ] La documentation sur FIGMA type mode d'emploi est réalisée (optionnelle)
- [ ] La documentation des usages est réalisée et disponible pour les développeurs
Lien du composant sur FIGMA : https://www.figma.com/design/m2tWjSODYdgi5POFx0cmJr/Synapse?m=auto&node-id=317-1396

**Critères d'acceptances pour la revue du développement (destinée à la publication)** 

- [ ] Le composant est fonctionnel
- [ ] Le composant est responsive (mobile, tablet et desktop)
- [ ] Le composant répond aux critères d'accessibilité (test Tanaguru + A11y linter)
- [ ] Le composant passe les tests du DS
- [ ] La documentation API et exemples est réalisée
- [ ] Qualité code : les :deep des composants sont retirés
- [ ] Le composant est conforme aux maquettes (tokens)

**Comment by valentinbecquet** [comment]
La version tablet n'est pas nécessaire néanmoins merci d'indiquer dans la documentation quand passer du desktop au mobile.

- [ ] @JadeJnw merci de mettre à jour le button pour tous les variants vers le button de la librairie synapse et non DS CNAM VueDot/Bridge. Certaines routes ne sont pas correctes.
- [ ] Merci d'affecter les variables en marges et radius (les valeurs sont correctes mais écrites à la main)
- [ ] Merci de documenter le composant pour permettre sa bonne intégration par @4dr1en.

@JadeJnw et @4dr1en : composant prioritaire pour le sprint en cours

Dès que c'est bon, merci @JadeJnw de mettre le ticket dans prête / dév. et d'en informer @4dr1en.
Côté Design le composant est conforme aux exigences des tokens et peut passer en intégration

**Comment by valentinbecquet** [comment]
Réflexion sur l'usage du store en cours

**Comment by valentinbecquet** [comment]
Ok on pousse en l'état

**Comment by DavidFyon** [comment]
![Image](https://github.com/user-attachments/assets/84856c73-ad41-4dba-b612-ba7e80fe9498)
