### ISSUE TITLE
DialogBox : bouton disabled puis enabled

### ISSUE THREAD

**Issue by tibolelievre** [assurance-maladie-digital/design-system#3700]
## Description

Un élément qui change d'état (disabled-> enabled par exemple), ne devient pas navigable au clavier.

## Comment reproduire

Nous utilisons une DialogBox pour saisir un texte avec un bouton Annuler (qui ferme la DialogBox) et un Valider (qui enregistre la saisie)

Le bouton Valider est disabled tant qu'il n'y a pas au moins 10 caractères saisis.

Lorsque les 10 caractères sont saisis, il est enabled mais il n'est pas navigable au clavier.

## Comportement attendu

Un élément qui change d'état (disabled-> enabled par exemple), devient navigable au clavier.

## Priorisation

- Prioritaire

## Projet

P1 - Compte AS Refonte

## Contacts

Thibaut LELIEVRE - [thibaut.lelievre@assurance-maladie.fr](mailto:thibaut.lelievre@assurance-maladie.fr)

## Commentaires 

Pistes de correction :

Rendre accessible la méthode setEventListeners pour pouvoir redéfinir les éléments navigables au clavier ?

**Comment by 4dr1en** [comment]
vous pouvez modifier les propriétés du boutton valider en utilisant la props `vuetify-options` et surveiller le clic sur le boutton grace a l'évènement `confirm`.

```typescript
<template>
	<div>
		<VBtn
			color="primary"
			@click="dialog = true"
		>
			Afficher le composant
		</VBtn>

		<DialogBox
			v-model="dialog"
			title="Enregistrement"
			cancel-btn-text="Retour"
			confirm-btn-text="Enregistrer"
			:vuetify-options="options"
			@cancel="dialog = false"
			@confirm="confirm"
		>
			<VTextField
				v-model="textField"
				:rules="rules"
				validate-on-blur
			/>
			<p>Souhaitez-vous procéder à l’enregistrement ?</p>
		</DialogBox>
	</div>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	@Component
	export default class DialogBoxBtnText extends Vue {
		dialog = false;
		textField = '';
		rules= [
			(value: string): string|true => (value.length >= 10 ? true : '10 caractères minimum')
		];
		get valid(): boolean {
			return this.textField.length >= 10;
		}
		get options(): Record<string, unknown> {
			return {
				confirmBtn: {
					disabled: !this?.valid,
					tabIndex: -1
				}
			};
		}

		confirm(): void {
			alert('user input:' + this.textField);
			console.log('user input:' + this.textField);
			this.dialog = false;
		}
	}
</script>
```

**Comment by tibolelievre** [comment]
Bonjour, 

Je ne vois pas en quoi cela rend le bouton "Enregistrer" accessible au clavier via la tabulation lorsqu'il n'est plus disabled.
