### ISSUE TITLE
Composant FiltersInline manquant

### ISSUE THREAD

**Issue by antoinecnam** [assurance-maladie-digital/design-system#3704]
## Description

FiltersInline n'existe pas en étant sur un projet nuxt3

## Comment reproduire

```
import {
	FiltersInline,
} from "@cnamts/synapse-bridge";
```

## Captures d'écran

![image](https://github.com/user-attachments/assets/ba25d052-f5a5-4337-883d-2d5c8165433c)

## Priorisation

- Très prioritaire

## Projet

ssa_portail_as_administration/aspa_x

## Contacts

Antoine Gosset dev front

**Comment by 4dr1en** [comment]
Bonjour, ce composant a été ajouté dans la version _v1.4.9-alpha.0_
