### ISSUE TITLE
PageContainer

### ISSUE THREAD

**Issue by valentinbecquet** [assurance-maladie-digital/design-system#3705]
**Mise à niveau PageContainer**

**Besoin**
Mettre en conformité le composant PageContainer pour Synapse 
Lien vers composant VueDot/Bridge : https://digital-design-system.netlify.app/composants/layout/page-container

- Ce composant est à concevoir sous vue3 en accord avec v3.vuetify
- Contrôler les marges en accord avec les tokens
- Optimiser le composant (code) pour l'éco-conception

Le découpage du composant peut être différent entre la librairie développée (Synapse) et l'UI kit des designers selon les besoins du logiciel FIGMA. Néanmoins, en cas de différence, une documentation type mode d'emploi sur FIGMA doit être réalisé.

**Critères d'acceptances pour la revue de la conception** 

- [x] Le composant intègre sur FIGMA, en cas d'utilisation de composant vuetify, les propriétés vuetify utiles au design
- [x] Le composant est maquetté sur FIGMA (tous les états + devices mobile, tablet et desktop)
- [x] La documentation sur FIGMA type mode d'emploi est réalisée (optionnelle)
- [x] La documentation des usages est réalisée et disponible pour les développeurs
Lien du composant sur FIGMA : _à indiquer par les designers_

**Critères d'acceptances pour la revue du développement (destinée à la publication)** 

- [x] Le composant est conforme aux maquettes (tokens)
- [x] Le composant est fonctionnel
- [x] Le composant est responsive (mobile, tablet et desktop)
- [x] Le composant répond aux critères d'accessibilité (test Tanaguru + A11y linter)
- [x] Le composant passe les tests du DS
- [x] La documentation API et exemples est réalisée

**Comment by DavidFyon** [comment]
![Image](https://github.com/user-attachments/assets/9b7d19d8-a08e-4ce3-ab09-fc552fcbf6d3)
