### ISSUE TITLE
SkipLink

### ISSUE THREAD

**Issue by valentinbecquet** [assurance-maladie-digital/design-system#3708]
**Mise à niveau SkipLink**

**Besoin**
Mettre en conformité le composant SkipLinkpour Synapse 
Lien vers composant VueDot/Bridge : https://digital-design-system.netlify.app/composants/navigation/skip-link/

- Ce composant est à concevoir sous vue3 en accord avec v3.vuetify
- Contrôler les couleurs, font, marges en accord avec les tokens
- Optimiser le composant (code) pour l'éco-conception

Point de vigilance sur l'accessibilité : contrôler le respect des critères RGAA (focus order : https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#12.7 ; https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#12.8 ; https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#12.9 ; https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#12.11) 

Le découpage du composant peut être différent entre la librairie développée (Synapse) et l'UI kit des designers selon les besoins du logiciel FIGMA. Néanmoins, en cas de différence, une documentation type mode d'emploi sur FIGMA doit être réalisé.

**Critères d'acceptances pour la revue de la conception** 

- [x] Le composant est maquetté sur FIGMA (tous les états + devices mobile, tablet et desktop)
- [ ] La documentation des usages est réalisée et disponible pour les développeurs
Lien du composant sur FIGMA : _à indiquer par les designers_

**Critères d'acceptances pour la revue du développement (destinée à la publication)** 

- [x] Le composant est conforme aux maquettes (tokens)
- [x] Le composant est fonctionnel
- [x] Le composant est responsive (mobile, tablet et desktop)
- [x] Le composant répond aux critères d'accessibilité (test Tanaguru + A11y linter)
- [x] Le composant passe les tests du DS
- [x] La documentation API et exemples est réalisée
- [x] La documentation sur l'accessibilité est présente (a minima, indiquer les critères concernés par ce composant)

**Comment by rquesnel** [comment]
Lien du composant Figma :
https://www.figma.com/design/m2tWjSODYdgi5POFx0cmJr/Synapse?m=auto&node-id=4230-12234&t=NJboPc9z3HaR1vEJ-1

**Comment by DavidFyon** [comment]
TODO: remplacer lien target (stories) une fois la doc publiée

**Comment by DavidFyon** [comment]
![Image](https://github.com/user-attachments/assets/ee9596f7-5a92-47bc-b1b8-6ffef3c8f40a)
