### ISSUE TITLE
Ajout attribut aria-describedby à la div contenant "role = dialog" composant DialoxBox

### ISSUE THREAD

**Issue by Jeremy-CNAM** [assurance-maladie-digital/design-system#3721]
## Description

Pour le composant DialogBox, dans un soucis d'accessibilité, ajouter la possibilité de mettre une propriété "aria-describedby" dans la div qui contient "role=dialog".

## Comportement attendu

Que la div qui contient "role = dialog" du composant DialogBox puisse avoir un attribut "aria-describedby" pour que ce composant soit accessible.

## Captures d'écran
Cette div doit pouvoir posséder "aria-describedby"
![image](https://github.com/user-attachments/assets/e4742874-2152-4161-9ef7-0ac5a4b1257e)

## Priorisation
- Prioritaire

## Projet
P1 - Compte AS Refonte

## Contacts
Jérémy LAMY - dev front refonte

**Comment by DavidFyon** [comment]
@Jeremy-CNAM un attribut aria-describedby a été rajouté sur le contenu du DialogBox mais il n'est pas possible de la rajouté directement sur le div contenant role=dialog (Vuetify ne le permet pas).

**Comment by tibolelievre** [comment]
Désolé de revenir la dessus mais je crois que l'auditrice s'est trompée, car elle a indiqué : 

![image](https://github.com/user-attachments/assets/839e1665-c324-4e15-8b6c-c03199fcadd4)

Je pense qu'elle voulait dire aria-labelledby (au lieu de aria-describedby) et du coup nous avons fait une mauvaise demande.

C'est ce qui semble être confirmé dans la [notice accede web de la fenêtre modale.](https://www.accede-web.com/notices/interface-riche/fenetres-modales/)

Donc la correction serait d'ajouter un aria-labelledby avec la valeur de l'id du titre (attention plusieurs modales peuvent être présentes dans la même page html)

**Comment by valentinbecquet** [comment]
Merci @tibolelievre on va regarder ça

**Comment by tibolelievre** [comment]
Ce n'est toujours pas correct, l'attribut aria-labelledby doit contenir l'id du titre (comme je l'avais indiqué) et non le contenu du titre…
