### ISSUE TITLE
DialogBox : bouton disabled puis enabled (cf v2)

### ISSUE THREAD

**Issue by DavidFyon** [assurance-maladie-digital/design-system#3725]
https://github.com/assurance-maladie-digital/design-system/pull/3712

**Comment by 4dr1en** [comment]
déjà traité sur cette branche: origin/fix/dialogBox-focus-dynamic-elements

**Comment by 4dr1en** [comment]
https://github.com/assurance-maladie-digital/design-system/pull/3713
