### ISSUE TITLE
FranceConnectBtn

### ISSUE THREAD

**Issue by valentinbecquet** [assurance-maladie-digital/design-system#3744]
**Mise à niveau FranceConnectBtn**

**Besoin**
Mettre en conformité le composant FranceConnectBtn pour Synapse 
Lien vers composant VueDot/Bridge : https://digital-design-system.netlify.app/composants/boutons/france-connect-btn

- Ce composant est à concevoir sous vue3 en accord avec v3.vuetify
- Contrôler les marges, les couleurs et les fonts en accord avec les tokens
- Optimiser le composant (code) pour l'éco-conception et inclure le même niveau de permissivité que celui du Bridge (slots, personnalisation des labels, etc.).
- Doit respecter les guidelines : https://docs.partenaires.franceconnect.gouv.fr/fs/integration-graphique/integration-bouton-fc/

Le découpage du composant et de ses sous-composants peut être différent entre la librairie développée (Synapse) et l'UI kit des designers selon les besoins du logiciel FIGMA. Néanmoins, en cas de différence, une documentation type mode d'emploi sur FIGMA doit être réalisé.

**Critères d'acceptances pour la revue de la conception** 

- [x] Le composant intègre sur FIGMA, en cas d'utilisation de composant vuetify, les propriétés vuetify utiles au design
- [x] Le composant est maquetté sur FIGMA (tous les états + devices mobile, tablet et desktop)
- [ ] La documentation sur FIGMA type mode d'emploi est réalisée (critère optionnel, à cocher si accomplie ou non nécessaire)
- [ ] La documentation des usages est réalisée et disponible pour les développeurs
Lien du composant sur FIGMA : _à indiquer par le designer_

**Critères d'acceptances pour la revue du développement (destinée à la publication)** 

- [x] Le composant est fonctionnel
- [x] Le composant est responsive (mobile, tablet et desktop)
- [x] Le composant répond aux critères d'accessibilité (test Tanaguru + A11y linter)
- [x] Le composant passe les tests du DS
- [x] La documentation API et exemples est réalisée
- [x] Le composant est conforme aux maquettes (tokens)
- [x] Le composant respecte les guidelines de franceconnect (DS de l'état)

**Comment by rquesnel** [comment]
Lien du composant Figma :
https://www.figma.com/design/m2tWjSODYdgi5POFx0cmJr/Synapse?m=auto&node-id=350-12196&t=NJboPc9z3HaR1vEJ-1

**Comment by valentinbecquet** [comment]
L'état disabled n'existe pas et n'a aucun intérêt opérationnel. A supprimer du Figma @valentinbecquet.

**Comment by DavidFyon** [comment]
![Image](https://github.com/user-attachments/assets/0f9e6011-1cf6-4bda-a1ab-7d08aac7a61b)
