### ISSUE TITLE
Dark mode do not work with some components

### ISSUE THREAD

**Issue by liollury** [assurance-maladie-digital/design-system#3751]
## Description

Pour un certain nombre de composants comme le footer ou les tableToolbar, le passage en theme **dark** ne fonctionne pas.

## Comment reproduire

1. Utiliser **FooterBar** et **TableToolbar** dans un composant Vue.
2. Passer en mode sombre :

```js
const theme = useTheme();
theme.global.name.value = 'dark';
```

## Reproduction minimale

NA

## Comportement attendu

Les composants on un mode sombre, utilise les variable du theme et ne reste pas blanc.

## Captures d'écran

![image](https://github.com/user-attachments/assets/11c55ab4-2313-41a8-bf6c-8943dd93e8e1)
![image](https://github.com/user-attachments/assets/ddd748c3-d70c-45c9-ba95-7aee0570460f)

## Environnement

- Librairie : @cnamts/synapse-bridge 3.0.1 @cnamts/design-tokens 2.16.8
- Version : SK Vue3
- OS : Windows
- Navigateur : Chrome

## Priorisation

Peu prioritaire 

## Projet

PDO

## Contacts

Olivier LE LAY

## Commentaires 

Pour le **FooterBar** et certains autres composants, un element de style semble être appliqué pour la classe _theme--dark_, or la classe appliqué par vuetify est _v-theme--dark_.

**Comment by VachetVirginie** [comment]
Bonjour, les fixs relatifs à la TableToolbar seront disponibles avec la nouvelle version livrée cette semaine, pour le FooterBar avez-vous ajouter la props dark comme dans l'exemple ci-joint? 

``` vue 

<template>
	<VApp>
		<PageContainer>
			<FooterBar
				v-bind="docProps"
				dark
			>
				<p class="text--secondary mb-0">
					Contenu supplémentaire.
				</p>
			</FooterBar>
		</PageContainer>
	</VApp>
</template>

<script lang="ts">

import PageContainer from '@/elements/PageContainer/PageContainer.vue';
import FooterBar from '@/patterns/FooterBar/FooterBar.vue';
import { defineComponent } from 'vue';

export default defineComponent({
	components: {
		PageContainer,
		FooterBar
	},
	data () {
		return {
			docProps : {
				sitemapRoute: '/',
				cguRoute: '/',
				cookiesRoute: '/',
				legalNoticeRoute: '/',
				a11yStatementRoute: '/'
			}
		};
	}
});
</script>

```

**Comment by liollury** [comment]
Bonjour,

merci pour le retour. Je n'ai pas ajouter la propriété **dark** étant donné que j'ai passer le theme global a **dark**. 
Le forcage manuel comme dans votre exemple fonctionne de mon coté.
Comme les autres composants réagissent correctement au thème, le footer ne devrait-il pas faire de même sans avoir besoin de l'explicité ?
