### ISSUE TITLE
problèmes avec le composant <PasswordField>

### ISSUE THREAD

**Issue by asicfr** [assurance-maladie-digital/design-system#3754]
## Description

Suite aux développements de la page d'authentification, nous rencontrons deux problèmes avec le composant <PasswordField> .

- Problème d'interprétation des mots de passe enregistrés : Nous avons observé que lorsque le navigateur tente de remplir automatiquement le champ de mot de passe avec des données enregistrées, le composant ne semble pas interpréter correctement cette saisie automatique. En effet, le mot de passe est reçu comme une chaîne vide dans notre code. Cela ne se produit pas lorsque nous utilisons un composant standard tel que <VTextField type="password"/>. Pourriez-vous nous confirmer si ce comportement est intentionnel ou s'il s'agit d'un dysfonctionnement ?

- Gestion de l'appui sur la touche Entrée : Nous avons également remarqué que le composant ne gère pas l'appui sur la touche Entrée pour soumettre le formulaire. Est-ce un choix de conception délibéré ou est-ce un comportement qui devrait être implémenté ?

## Environnement

"@cnamts/design-tokens": "^2.12.0",
"@cnamts/eslint-config-vue": "^2.14.0",
"@cnamts/form-builder": "^2.14.0",
"@cnamts/human-uc-cp17_h": "^1.0.3",
"@cnamts/vue-dot": "^2.14.0",

## Priorisation

- prioritaire 

## Projet

RESID

## Contacts

Stephane Labbe

**Comment by DavidFyon** [comment]
@asicfr La gestion de la touche entrée à été rajoutée, par contre n'avons pas noté de soucis avec l'autocomplete (firefox/chrome/safari).
