### ISSUE TITLE
NitField et validation vuetify ko

### ISSUE THREAD

**Issue by xontik** [assurance-maladie-digital/design-system#3756]
## Description

Le composant NirFIeld ne mets plus à jour le status de validation de vuetify

<img width="1152" alt="image" src="https://github.com/user-attachments/assets/7a51967e-6c50-4ea5-bdd8-5ac206241141">

## Comportement attendu

Le status de validation vuetify doit se mettre a jour pour permetre de griser le bouton submit

- Librairie : @cnamts/synapse-bridge
- Version : 3.0.0

## Projet

Inva Pallier 1

**Comment by eartru-N** [comment]
Je confirme avoir le même comportement sur le projet RENTE mais avec le isValid à null.

**Comment by DavidFyon** [comment]
Bonjour, le soucis à été corrigé sur la version 3.0.1
