### ISSUE TITLE
Format du Nir Dans le champ

### ISSUE THREAD

**Issue by bborlet** [assurance-maladie-digital/design-system#3809]
## Description

Le format du nir n'est pas validé correctement

## Comment reproduire

Saisir le nir : 1 23 45 6B 766 776

<img width="563" alt="image" src="https://github.com/user-attachments/assets/da6a3eb0-c682-4807-92d4-d90ee0d1cfe0">

## Comportement attendu

Le format doit être validé par rapport au nir correct

## Environnement

- Librairie :@cnamts/synapse-bridge
- Version : 3.0.4
- OS : macOs
- Navigateur : Chrome

## Projet

Gedi - Refonte inva pallier 1

## Contacts

Benjamin Borlet

**Comment by DavidFyon** [comment]
@bborlet peux-tu nous préciser pourquoi il n'est pas validé correctement ?

**Comment by bborlet** [comment]
Comment ca pourquoi ? Le nir de l'exemple ne respecte pas le format d'un nir (le 6 avant le B).
