### ISSUE TITLE
DatePicker ne renvoie pas la valeur tant que la date n'est pas ISO

### ISSUE THREAD

**Issue by mbelluzzi** [assurance-maladie-digital/design-system#3828]
Bonjour, je rouvre une autre issue pour ce problème, je ne pouvais pas rouvrir l'ancienne.

Les deux events (input ou change) ne renvoie pas la string tant que celle-ci n'est pas une date au bon format:

![{F2A6E130-B04D-422D-BD7B-88FCAEC28BF0}](https://github.com/user-attachments/assets/86276520-6ef9-47c8-8f23-8c2f7b5efaca)

![{85B5D344-2F87-45AE-A334-1D13B8A51C57}](https://github.com/user-attachments/assets/11dfbef8-8178-4f0a-8768-3e9ac951ef8e)

![{3F808166-FD22-4DC1-B204-D829944C1666}](https://github.com/user-attachments/assets/de176d14-20ff-4e6a-8488-b302fe961fa8)

Le cas d'usage ici est de pouvoir reset la valeur du champ à l'intérieur avec un bouton "réinitialiser les champs", ce qui est impossible puisque la valeur retournée par le composant reste une string vide tant que la valeur n'est pas une date ISO

_Originally posted by @mbelluzzi in https://github.com/assurance-maladie-digital/design-system/issues/3450#issuecomment-2456831200_

**Comment by valentinbecquet** [comment]
Merci pour ton retour. Nous allons essayer d'embarquer ton issue dans ce sprint (5/11 - 25/11) pour une publication semaine du 18/11.

**Comment by DavidFyon** [comment]
Bonjour,

Le comportement est normal car le champ n'est pas valide :
![Image](https://github.com/user-attachments/assets/1638d279-48ea-45f2-8561-5f75aa1220aa)

Toutefois cela peux être résolu de cette façon :

```vue
<template>
	<div class="pa-4">
		<DatePicker
			v-if="show"
			ref="datepicker"
			v-model="selectedDate"
			birthdate
			date-formate="DD/MM/YYYY"
			date-format-return="YYYY-MM-DD"
			outlined
			clearable
			label="Date de naissance"
			@keyup.enter="onEnter"
			@input="onFieldInput"
		/>
		<VBtn @click="reset">
			Reset
		</VBtn>
	</div>
</template>

<script lang="ts">
	import Vue from 'vue';
	import Component from 'vue-class-component';

	@Component
	export default class Playground extends Vue {
		selectedDate: string | null = null;
		show = true;

		onEnter(): void {
			console.log('ENTER', this.selectedDate);
		}

		onFieldInput(): void {
			console.log('INPUT', this.selectedDate);
		}

		reset(): void {
			this.show = false;
			this.$nextTick(() => {
				this.show = true;
			});
		}
	}

</script>
```

**Comment by valentinbecquet** [comment]
@mbelluzzi ça te va ?

**Comment by mbelluzzi** [comment]
Le workaround fonctionne, mais c'est quand même étrange d'avoir une règle de validation incorporé au composant qui empêche de reset la valeur affichée. Est-ce qu'il y aura une évolution future concernant cet aspect ?
