### ISSUE TITLE
[V3] PaginatedTable : Textes d'indication

### ISSUE THREAD

**Issue by ArthurBrgn** [assurance-maladie-digital/design-system#3854]
Les textes d'indication sur le composant PaginatedTable sont en anglais par défaut dans la V3 : 

![image](https://github.com/user-attachments/assets/13d827d6-3663-41e3-9749-1409ae01c6f8)

Voici le code (repris de la doc) : 

`<PaginatedTable
		:headers="tableHeaders"
		:items="[]"
		:items-per-page="5"
		:options="tableOptions"
/>`

J'ai regardé le code d'un ancien projet et par défaut il semble que les textes étaient bien en français

J'arrive à le contourner en passant des props présentes dans la doc de vuetify mais il faudrait se réaligner avec la V2.

Merci d'avance

**Comment by VachetVirginie** [comment]
Bonjour, 
Il faut rajouter dans le nuxt.config.ts: 
``` vue
import { fr } from 'vuetify/locale' 
vuetify: {
		vuetifyOptions: {
			locale: {
				locale: 'fr',
				messages: { fr },
			}, ...
``` 
Le fix sera disponible dans la prochaine version du starterKit
