### ISSUE TITLE
[0.0.5] FooterBar : Fond blanc en mode "dark"

### ISSUE THREAD

**Issue by CodazziS** [assurance-maladie-digital/design-system#3879]
## Description

Le comportement par défaut de la footer barre est un fond blanc avec du texte blanc : 
![image](https://github.com/user-attachments/assets/6e6c59f0-8af4-4edc-95dd-a56c4e3d8288)

## Reproduction minimale

```
<template>
  <FooterBar
    :version="appInfo.version"
    :link-items="footerLinks"
    :light="false"
  />
</template>
```

**Comment by DavidFyon** [comment]
Bonjour, en prenant le SK Synapse avec la dernière version du DS (3.0.8) cela devrait être corrigé.
