### ISSUE TITLE
Vue-Dot -  DataList : erreur lorsqu'on a un entier en valeur

### ISSUE THREAD

**Issue by Linaida** [assurance-maladie-digital/design-system#469]
Bonjour,

Serait-il possible de modifier le type de retour sur la fonction `getItemValue` du `DataListItem` de cette forme : 
```
 		get itemValue(): string  | number {
			return this.value || this.placeholder;
		}
```

Car si on a un entier comme valeur cela provoque une erreur et la liste ne s'affiche pas.

Merci :) 

Linda

**Comment by deraw** [comment]
Hello !

Le soucis que je vois avec ça c'est que si le nombre est `0` ou `-0`, avec le code actuel ça affichera le placeholder :thinking:
Il faudrait qu'on ajoute une condition, mais c'est peut-être plus propre de transformer la valeur en chaîne avant ?

**Comment by Linaida** [comment]
PR en cours  : https://github.com/assurance-maladie-digital/design-system/pull/532
