### ISSUE TITLE
Filtres sur les colonnes de tableaux

### ISSUE THREAD

**Issue by BaptisteCool** [assurance-maladie-digital/design-system#733]
## Description

Ajout d'un composant pour filtrer les lignes d'un tableau.

Dans une première version, le composant doit porter uniquement la partie graphique (voir pièces jointes), et s'utiliser avec l'API suivante :

```vue
<FilterModule
	:filters="filters"
	@filter-selected="filterSelected"
/>
```

```ts
// Définition des filtres
filters = [
	{
		label: 'Label du filtre',
		key: 'filterKey',
		form: {} // Objet FormFieldList
	}
];

// Définition du payload de l'événement
filterSelected(filters) {
	console.log(filters);
	// [
	// 	{
	//		key: 'filterKey',
	//		value: formValue
	//	}
	// ]
}
```

## Pièces jointes

![image](https://user-images.githubusercontent.com/6760432/100078445-cfdd3780-2e43-11eb-82c5-838614b27271.png)
![image](https://user-images.githubusercontent.com/6760432/100078568-f3a07d80-2e43-11eb-8d8f-d3df65edf961.png)
![image](https://user-images.githubusercontent.com/6760432/100078645-04e98a00-2e44-11eb-9003-522c47a2b9e9.png)

## Priorisation

- [ ] Peu prioritaire 
- [x] Prioritaire
- [ ] Très prioritaire

## Projet

Corona back-office -> repo: declare-ihm-agent

**Comment by BaptisteCool** [comment]
Le besoin a été qualifié comme étant une demande valide (pas besoin de plus d'informations pour le moment).

**Comment by BaptisteCool** [comment]
Demande accepté et sera estimé prochainement

**Comment by PYKEngine** [comment]
New branch filter-workflow created

**Comment by deraw** [comment]
On étudiera une deuxième version où l'on passerait les données à filtrer directement au composant et où celui-ci filtrerait effectivement les données, cela simplifierait l'utilisation du composant dans les cas simples pour l'utilisateur
