### ISSUE TITLE
Atelier sur les couleurs et le thème

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#894]

**Comment by francoiscoue** [comment]
### CR atelier

**Questions :**
Gestion des chartes différentes ? 

**Réponses :**
Pas de configuration par composant possible dans Vuetify (avant V3).
Eviter d'écraser les couleurs des composants Vuetify
On reste sur les 7 variables définies par Vuetify
Les variations (plus clair/ plus foncé) sont gérées par Vuetify

**Actions :** 
- [ ] - Implication de la DICOM pour organisation et gouvernance des chartes (@francoiscoue , avec communauté Design)
- [ ] - Création d'alias notamment pour les couleurs textes possible sur demande

**Comment by deraw** [comment]
On reprend le thème avec ces modifications :
- primary : #0C419A
- secondary : #007FAD
