### ISSUE TITLE
Composant Bouton réutilisable

### ISSUE THREAD

**Issue by jessy-manc** [assurance-maladie-digital/design-system#911]
## Description
Je propose la création un composant bouton réutilisable
De cette façon une application aurait un design constant
De la même manière il pourrait y avoir des champs usuels de formulaire :
-Input String
-Input Textarea
-Input Number
-Input Date
-Input Radio
-Input Checkbox
Il existe le FormFieldList, mais la doc n'est pas très claire.

Merci.

## Pièces jointes
https://www.codegram.com/blog/create-a-reusable-button-with-vue-dynamic-components/
https://codeburst.io/creating-reusable-components-with-vue-js-button-component-503167facfde
https://codepen.io/xiaomingming/pen/yVmMOz
https://stackoverflow.com/questions/52901023/create-reusable-button-component-with-vue-js

## Priorisation
- [ ] Peu prioritaire 
- [ ] Prioritaire
- [ ] Très prioritaire

## Projet
N/A

## Contacts
N/A

**Comment by deraw** [comment]
Bonjour,

Merci pour votre proposition !

Nous utilisons Vuetify comme base pour créer des composants de plus haut niveau, vous pouvez donc utiliser le [composant `VBtn` de Vuetify](https://vuetifyjs.com/en/components/buttons/).

Pour les champs de formulaire, il y a également ces composants dans Vuetify, comme par exemple le [composant `VTextarea`](https://vuetifyjs.com/en/components/textareas/).
Nous avons aussi dans notre librairie le [composant `FormField`](https://digital-design-system.netlify.app/composants/form-field/) qui permet d'afficher un champ de formulaire représenté par un objet JSON, bien qu'il manque encore de quelques champs élémentaires comme les boutons radios ou les cases à cocher.

Nous travaillons sur une refonte complète de la documentation pour qu'elle soit plus compréhensible et contienne plus d'informations. Merci pour votre retour sur la page du composant `FormFieldList`, je le prend en compte directement dans la nouvelle version de la documentation !
