### ISSUE TITLE
R&D tests de non regression

### ISSUE THREAD

**Issue by deraw** [assurance-maladie-digital/design-system#954]
- Il s'agit de comparer d'autres outils de tests de non-régression visuelle avec Storybook
- Vérifier le pour et le contre etc

**Comment by mmi16389** [comment]
Lors de la recherche des outils de tests de non-regression visuel(aussi test visuel), **vue-styleguidist.**, **strorybook**, a été les choix les plus pertinents. Mais après avoir testé et verifié chacun de ces outils.  Il me semble que  **vue-styleguidist.** est limité par rapport nos besoins. Ce rapport se focalise sur storybook(les points forts et points faibles)

En effet,  **vue-styleguidist.**, est une  autre approche de rédaction de la documentation de composants d'un design system, à la manière de vuepress(md..etc), jsdocc..Etc. Mais beaucoup plus riche.  Le point bloquant est qu'il n'est pas interactif. Nous avons déjà accompli ce besoin ici (https://digital-design-system.netlify.app/) documentation officielle de notre design system.

**strorybook**
Pareillement, Storybook est un environnement de développement pour les composants UI. Il nous permet de visualiser nos composants avec leurs différents états et de les développer de manière à ce qu’ils soient interactifs.

À celui-ci s’ajoutent des modules complémentaires qui vont nous permettre, par exemple : d’afficher dynamiquement le code du composant ; de montrer les évènements produit par ce dernier ; de modifier les propriétés ; d’écrire des notes ; d’afficher nos composants sous différentes tailles d’écrans etc.

Ils dispossent aussi des formats (Markdown X: mdx) favorisant l'ecriture d'une documentation.
- l'apprentissage à la redaction de test visuel est plutot moyen; pour du long terme vaut mieux les écrires en suivant la documention officiel. 
- il exist un vue cli strorybook, mais il se trouve que quelques addons(modules, dépendances)  utilisés ne seront plus maintenu à partir de la version 7.   Version actuelle: 6.2.3
- Storybook est developpé en `React ` , si nous souhaitons créer des nouveaux modules, addons pour storybook nous devons le faire avec React.   

Le resultat de la recherche se trouve via cettre branche : feat/storybook

Quelques lien utils: 
[**vue-styleguidist.**]([url](https://vue-styleguidist.github.io/nuxtjs/))
**strorybook**
1- https://5a375b97f4b14f0020b0cda3-kteijjgcjy.chromatic.com/?path=/docs/addons-actions--arg-types-example
